### ISSUE TITLE
go-version: 1.x not resolving to Go 1.16

### ISSUE THREAD

**Issue by fsouza** [actions/setup-go#105]
Hi there! 👋 

Go 1.16 is out, and I was expecting to get it with `go-version: 1.x` (or just `go-version: 1`), but it looks like that isn't available yet.

Perhaps someone has to trigger the workflows to [build 1.16](https://github.com/actions/go-versions/blob/main/.github/workflows/build-go-packages.yml) and [update the manifest](https://github.com/actions/go-versions/blob/main/.github/workflows/create-pr.yml) in the go-versions repo? (though it may require updating the config?)

**Comment by fsouza** [comment]
Sorry, opened this before understanding how it works. Closing in favor of https://github.com/actions/virtual-environments/issues/2728.

**Comment by maxim-lobanov** [comment]
@fsouza , you can specify version as `1.16.x` and it will resolve automatically so you don't need to wait until Go is added to images.

**Comment by fsouza** [comment]
@maxim-lobanov I know. My goal was to not to have to do that x)
