### ISSUE TITLE
Document what happens when '.x' version is specified, such as '1.16.x'

### ISSUE THREAD

**Issue by x448** [actions/setup-go#115]
README.md should explain differences (if any) between specifying "1.16" vs "1.16.x".

Even if go-version documents this in the future, it would be user-friendly to document it (at least briefly) in setup-go.

**Comment by codefromthecrypt** [comment]
if anyone knows what the difference is now, do tell!

**Comment by Sergey-Murtazin** [comment]
Hi, @x448 !
As written in [readme](https://github.com/actions/setup-go#v2), we are using semver notation.
You can see how to use it [here](https://devhints.io/semver)

The `x` sign means that the version with the maximum available version number in place of this sign will be used.
For example:
- `1.7.x` goes to `1.7.3` if `1.7.3`  is the maximum `1.17` version
- `1.x` goes to `1.7.3` too if `1.7.3`  is the maximum `1` version

**Comment by x448** [comment]
Hi @Sergey-Murtazin,

It's too easy for users to confuse 1.16 as "use default 1.16 installed" vs "download latest 1.16.x to replace default 1.16".  Same confusion with 1.16.x.  Adding a short example to docs would be a reasonable & easy solution.

New users to GitHub won't be able to just try both 1.15 and 1.15.x to clear up the ambiguity because the default is Go 1.15.15 on ubuntu-latest and there' no newer 1.15.x available.  And specifying 1.16 or 1.16.x both grab 1.16.10 even though 1.16.11 has been available for 4 days.

Something like this clarification in the docs would be helpful to GitHub users:

```
Specifying 1.16 vs 1.16.x is [the same .../... different].

If the vm has 1.16.88 as the default Go 1.16 and 1.16.99 is available, then:
- 1.16 uses 1.16.__ because [it uses the default 1.16.88 already installed .../... downloads 1.16.99]
- 1.16.x uses 1.16.__ because [it uses the default 1.16.88 already installed .../... download 1.16.99]
```

**Comment by Sergey-Murtazin** [comment]
Hi, @x448!

Thanks for your proposal!
Currently [pull request](https://github.com/actions/setup-go/pull/178) in review.

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close this issue because we add a note about SemVer in scope of this [pull request](https://github.com/actions/setup-go/pull/164).  Besides, we're going to add check latest logic in scope of this [pull request](https://github.com/actions/setup-go/pull/186).

**Comment by x448** [comment]
Thanks for adding `check-version` feature!
