### ISSUE TITLE
Action cannot be used with Self hosted runner

### ISSUE THREAD

**Issue by MichaelKHTai** [actions/setup-go#116]
## Intro
**Type of issue**: Bug report

## Reproduce

1. On a clean linux machine (I tested on Ubuntu20.04, Ubuntu18.04 and Debian10).
2. Following the instruction in https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service, to create a self-hosted runner
3. Registrate it to your GitHub Account's runner
4. Create a sample repo which has access to that self-hosted runner
5. Create a GitHub config file
```
jobs:
  gotest:
    name: GoTest
    runs-on: [self-hosted, linux]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.*'
      - name: Go Env
        run: |
          go env
```
6. Get this error in `actions/setup-go@v2`, but it won't exit the pipeline.
```
(node:12435) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: a path argument must be provided
    at Object.<anonymous> (/github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:4752:18)
    at Generator.next (<anonymous>)
    at /github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:4692:71
    at new Promise (<anonymous>)
    at module.exports.672.__awaiter (/github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:4688:12)
    at Object.mkdirP (/github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:4751:12)
    at Object.<anonymous> (/github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:204:22)
    at Generator.next (<anonymous>)
    at /github-action-runner/_work/_actions/actions/setup-go/v2/dist/index.js:57:71
    at new Promise (<anonymous>)
```
7. This is a non stopping error, so in `go env` line, another error will occur.
```
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
```
8. Check the `go env` and you can find that `GOPATH`, `GOENV` are missing.

## Possible bugs

1. As the `$HOME` is not correctly exported and `GOCACHE` is `"off"`, `go` cannot run.
2. Besides, another possible problem may be in this part and thus get a `a path argument must be provided` error.
https://github.com/actions/setup-go/blob/3b4dc6cbed1779f759b9c638cb83696acea809d1/src/main.ts#L67-L73

**Comment by hdavidzhu** [comment]
@MichaelKHTai I'm facing the same problem (on an arm-based self-hosted runner.) Were you able to find a solution to this?

**Comment by jsirianni** [comment]
Same issue here

**Comment by divyansh-gupta** [comment]
@hdavidzhu @jsirianni @MichaelKHTai I am having the same problem, are you able to share a solution?

**Comment by hdavidzhu** [comment]
This is the workaround that worked for me:

```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # NOTE 2021-07-01: For ARM machines,
          # https://storage.googleapis.com/golang does not have an ARM-based
          # build for the latest version. I'm pinning it to the latest version
          # that has ARM-support. https://github.com/actions/setup-go#v2 falls
          # back to 'go dist' since the go-versions repository has no ARM-based
          # references.
          go-version: "1.15.11"
```

Hope it helps!

**Comment by julnamoo** [comment]
Having the same problem.
Tried `go-version` with 1.13 and 1.17 along with the below step:
```
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
```
The case of go 1.13 shows the same error message below:
```
Run actions/setup-go@v2
  with:
    go-version: 1.13
    stable: true
    token: ***
Setup go stable version spec 1.13
Found in cache @ /home/ubuntu/_tool/go/1.13.15/x64
Added go to the path
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
Error: Command failed: go env GOPATH
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
```

For go 1.17, despite a different message but it might trouble at the same line..
```
Successfully cached go to /home/ubuntu/_tool/go/1.17.2/x64
Added go to the path
missing $GOPATH
Error: Command failed: go env GOPATH
missing $GOPATH
```
https://github.com/actions/setup-go/blob/main/src/main.ts#L56-L65

I also have been looking for a workaround..

**Comment by Sergey-Murtazin** [comment]
Hello @MichaelKHTai!

I've tried to reproduce the issue with Ubuntu 20.04 virtual machine on Azure and your workflow but it works as expected. 
My test run: 
https://github.com/Sergey-Murtazin/go-gin-to-github-actions/runs/4092920091?check_suite_focus=true

Could you please provide more detailed steps how we can reproduce it?

**Comment by trentis** [comment]
I've been trying to do it recently following a guys examples. Any ideas whats going on? 

```sh
run actions/setup-go@v2
  with:
    go-version: 1.16
    stable: true
    token: ***
Setup go stable version spec 1.16
Attempting to download 1.16...
matching 1.16...
Acquiring 1.16.9 from https://github.com/actions/go-versions/releases/download/1.16.9-1319361009/go-1.16.9-linux-x64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword -C /runner-tmp/_temp/5626b643-4853-4039-a6a6-c89e5d24a391 -f /runner-tmp/_temp/00f53892-4b60-4bf5-8260-ad1776594521
Successfully extracted go to /runner-tmp/_temp/5626b643-4853-4039-a6a6-c89e5d24a391
Adding to the cache ...
Successfully cached go to /runner-tmp/_tool/go/1.16.9/x64
Added go to the path
missing $GOPATH
Error: Command failed: go env GOPATH
missing $GOPATH
```
I am using this repository for the GCE part. https://github.com/bharathkkb/gh-runners. Is it just implying theres no $GOPATH env?  I would've thought the action sets that up for me.

**Comment by Sergey-Murtazin** [comment]
Hi, @trentis !

Could you please provide public repo to reproduce your problem?

**Comment by divyansh-gupta** [comment]
For what it's worth, after trying to use this action and running into the same issues, this is what I had to do to get Go installed on an EC2 self hosted runner: https://github.com/cert-manager/aws-privateca-issuer/blob/master/.github/workflows/on-safe-to-test-label.yml#L72-L84

**Comment by vsafonkin** [comment]
Hi @divyansh-gupta, I've checked EC2 self hosted runner: https://github.com/vsafonkin/test-repo/runs/4431047966?check_suite_focus=true
It works as expected. 

@trentis, could you please check $HOME value in your workflow?
```
echo $HOME
```
GOPATH is defined as $HOME/go by default.

**Comment by pseudo-su** [comment]
I'm running into this problem as well and it seems to be because the `HOME` environment variable isn't guaranteed to be setup on self hosted runners.

**Comment by Melaninneal** [comment]
As a workaround, If you have access to your self hosted runner I was able to add `export HOME=/root` to the `/actions-runner/runsvc.sh` and restarted the service `/actions-runner/svc.sh`

**Comment by divyansh-gupta** [comment]
@vsafonkin I believe you are running on Ubuntu - that works for me as well. When I use Amazon Linux, that's when it does not work, and that's where my workaround is applied.

**Comment by vsafonkin** [comment]
@divyansh-gupta, could you check $HOME variable on your self-hosted runner?

**Comment by divyansh-gupta** [comment]
Yes there is no $HOME directory, which is why I set values manually: https://github.com/cert-manager/aws-privateca-issuer/blob/master/.github/workflows/on-safe-to-test-label.yml#L72-L84

**Comment by vsafonkin** [comment]
I believe the reason of issue is missing $HOME variable on the self-hosted runners. Issue is closed because we cannot resolve it from `setup-go` action side. Please, contact us if you have any questions.

**Comment by divyansh-gupta** [comment]
@vsafonkin The missing HOME variable makes it so that Go is not able to make default folders for GOPATH and GOCACHE and such - could we not modify this action to setup custom folders for these if HOME does not exist, just like I did in the example?

**Comment by vsafonkin** [comment]
@divyansh-gupta, I believe $HOME variable should not set by action, because it is not `setup-go` scope. We can define $HOME value incorrectly and this can cause some breaks on the user' self-hosted machine.

**Comment by divyansh-gupta** [comment]
Understood and agreed - however I meant creating a folder elsewhere, even in tmp, and setting GOPATH and GOCACHE there? At a minimum, this limitation and the workaround with setting the GO values yourself should be documented in the README. What do you think?
