### ISSUE TITLE
Why mandate go-version parameter?

### ISSUE THREAD

**Issue by kaihendry** [actions/setup-go#132]
Why not install a stable go version by default?

**Comment by rfjakob** [comment]
It's not mandatory. You can just use the go version that is already installed.
See https://github.com/rfjakob/gocryptfs/blob/e2d3834b1c4aec2544369361f4b572c4f80dc544/.github/workflows/ci.yml for an example.

**Comment by Sergey-Murtazin** [comment]
Hi, @kaihendry !
A stable go version is installed by default. You can change this behaviour using `stable: 'false'`

**Comment by kaihendry** [comment]
so stable false means ?

**Comment by Sergey-Murtazin** [comment]
Hi, @kaihendry 
A stable go version is any version that is not `beta` or `rc`.
It means 1.17.1, 1.17.2 and 1.17.3 are stable versions.

You can also use the default go version preinstalled on GitHub hosted runners without using `setup-go` action.  
Only stable go versions are preinstalled there. 

You can find installed go versions in [virtual-environment repo](https://github.com/actions/virtual-environments#available-environments).
For example, for [Windows 2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#go) the default version is `1.15.15`.

Also, you can check the default installed version using just `go version` command in your workflow.

I'm going to close this issue.  
Feel free to contact us if you have any questions.
