### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by Harmon758** [actions/setup-go#16]
I'm getting this error fairly consistently when using the action:
```
Run actions/setup-go@v1.0.2
  with:
    go-version: 1.10
##[error]API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
##[error]Node run failed with exit code 1
```

**Comment by damccorm** [comment]
Huh, interesting - 2 questions:
1) Are you able to share your repo where you're seeing this by chance? I can't get a repro
2) Are you only seeing it when running this action? Or is it a more general problem?

**Comment by nathany** [comment]
Also seeing this error [here](https://github.com/RobotsAndPencils/cache-money-client/pull/1)  after adding macOS to the build matrix. 

```
strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
```

It also appears to have cancelled my Windows and Linux builds?

<img width="1008" alt="limit" src="https://user-images.githubusercontent.com/4566/64042017-33cc5f80-cb1e-11e9-8c0b-3d9778c9f1b9.png">

**Comment by Bios-Marcel** [comment]
I experienced this too: https://github.com/Bios-Marcel/cordless/runs/208451699

Same IP, same symptoms. Depending on what the rate limit is, might it be possible to just delay the download instead of failing?

**Comment by kjk** [comment]
Another option would be to attribute the call not to anonymous user but to a given GitHub user.

Actions already provide `GITHUB_TOKEN` secret of the repo's owner. It's just a matter of plugging it into that API call.

It might not be possible to just access it from the action but it would be possible to define `github-token` argument to the action, use it if provided and document that to avoid this rate limit, the user can provide it as:

```yml
with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mvdan** [comment]
I think a reasonable temporary solution is to specify exact Go versions like `1.12.9` instead of `1.12.x`. This shouldn't require GitHub API calls, so it shouldn't have any rate limit issues.

**Comment by mvdan** [comment]
Hmm, I still sometimes run into API rate limit errors with versions like `1.13`. It fails with no helpful error when I specify `1.13.0`, so I think it's not doing the same as `1.13.x`.

It should be possible to download a specific version of Go with zero GitHub API calls, as one can download Go straight from golang.org. It's even possible to list all released versions via JSON without even hitting GitHub: https://golang.org/dl/?mode=json&include=all

**Comment by kjk** [comment]
+1 to https://golang.org/dl/?mode=json&include=all
It looks like using it would eliminate the rate-limited api call

**Comment by subosito** [comment]
@kjk @mvdan @damccorm  I've updated API call to use the golang-dl one. I didn't know about this.

**Comment by Bios-Marcel** [comment]
Would be nice to get this merged fast and push a minor release :D

**Comment by andreynering** [comment]
I'm also facing this issue. If this is already fixed, it'd be nice to have a release so people benefit of this.

**Comment by mvdan** [comment]
Big thanks to @hfaulds for taking care of merging the PR! I think this can be closed for now. I'll shout if I see these flakes again.
