### ISSUE TITLE
Support Go version `1.18beta1`

### ISSUE THREAD

**Issue by qdm12** [actions/setup-go#177]
**Description:** Support `go-version` `1.18beta1` (or have it as `1.18.0-beta1`/`1.18.x`)

**Justification:** We want to experiment with Go 1.18 beta1 fuzzing and generics features, and it adds extra bloat in our CI configuration to install Go 1.18beta1 for now.

**Are you willing to submit a PR?** No; I have looked a bit through the code but it looks like something would need to be added to the `go-versions` repository which we cannot create PRs to.

**Comment by skaldarnar** [comment]
I'm in a similar situation and did some digging in the code. Here's what I found:

The lookup in the manifest of [actions/go-versions](https://github.com/actions/go-versions) is only the first attempt for finding a release. It looks like the manifest only contains stable releases, so we'll naturally fall back to the second option. 

https://github.com/actions/setup-go/blob/fdeec47002800c39dbe2cd2ab93d5f853d14ba32/src/installer.ts#L51-L62

When trying to use `1.18beta1` (or `go1.18beta1`) I can find the log output I'd expect here:

```
Not found in manifest.  Falling back to download directly from Go
``` 

The second attempt to find the version is by running `getInfoFromDist` which in turn calls `findMatch` in `installer.ts`.

https://github.com/actions/setup-go/blob/fdeec47002800c39dbe2cd2ab93d5f853d14ba32/src/installer.ts#L78-L87

It tries to find a match in the [list of golang artifacts](https://go.dev/dl/?mode=json&include=all) based on the provided version and the system architecture and platform.

https://github.com/actions/setup-go/blob/331ce1d993939866bb63c32c6cbbfd48fa76fc57/src/installer.ts#L213-L230

One culprit, at least when running the action on `ubuntu-latest`, is that the architecture string cannot match. 
The call to `sys.getArch()` yields `"x64"` which matches with the specification given in the manifest file, see

https://github.com/actions/go-versions/blob/9d9bd2c789e30036e2f05c4f3022de47e15b557e/versions-manifest.json#L13-L18

However, the official golang artifact list uses `"amd64"` as identifier.
![image](https://user-images.githubusercontent.com/1448874/146678802-b072da95-4f76-4c86-ab43-bd25539fb17f.png)

Maybe this helps somebody to provide a fix for this.

**Comment by skaldarnar** [comment]
**Update:** I've got this working in a crude setup. Here's what I'm using right now:

I'm trying to build my little `gh` extension https://github.com/skaldarnar/gh-terasology with `go1.18beta1`.

https://github.com/skaldarnar/gh-terasology/blob/929a5be0db78e186214749ae42b935497da24c20/.github/workflows/release.yml#L14-L17

Therefore, I'm using a fork of https://github.com/cli/gh-extension-precompile to allow the usage of unstable releases. See https://github.com/cli/gh-extension-precompile/compare/trunk...skaldarnar:trunk for the changes.

That in turn uses a fork of https://github.com/actions/setup-go with a crude fix to hard-code the mapping from "x64" to "amd64". See https://github.com/actions/setup-go/compare/main...skaldarnar:main for the respective changes.

Not sure whether those changes are going in the right direction, though.

**Comment by acim** [comment]
As a workaround, just run your code inside Go container:

```
    runs-on: ubuntu-latest
    container: golang:1.18-rc-bullseye
    steps:
        ...
```

This way you don't need to setup go.

**Comment by Sergey-Murtazin** [comment]
Hi, @qdm12!

I couldn't reproduce your problem.
Please check my [WF](https://github.com/Sergey-Murtazin/gh-terasology/runs/4583033582?check_suite_focus=true).

Could you please provide some repro steps or public repo where your problem occurs?

**Comment by skaldarnar** [comment]
@acim  @Sergey-Murtazin thanks for your suggestions and for testing this again.

It indeed seems that just using the right way to specify the version does the job. 
Looks like the "x64" vs "amd64" part was misleading, and the actual issue was not writing the version number as it should be.

I just now saw that there is an explanation of the [supported version syntax](https://github.com/actions/setup-go#supported-version-syntax), but I did not get reading past the [V2 section](https://github.com/actions/setup-go#v2) 🙈 

I was able to make another test run on https://github.com/skaldarnar/gh-terasology/commit/b541c5f87e5c8cd2b5e99ad36c7b24a938ac62dc without my hacky workaround and it worked just fine 👍  
Sorry for all the fuzz here, no open questions or issues from my side.

**Comment by Sergey-Murtazin** [comment]
I'm glad that we could help you. 

I close this issue.
Feel free to contact us if you have any questions.

**Comment by qdm12** [comment]
Thanks everyone and @Sergey-Murtazin! The `stable: false` field fixed it 👍

**Comment by deefdragon** [comment]
A recommendation for the future, it may be worth adding a note to the `Supported version syntax` section of the readme that unstable versions need `stable: false`. Or potentially adding an inputs table with both the format information and the stable input described.

I was personally looking for the way to import the beta, and missed the "Matching an unstable pre-release" example adding said input.
