### ISSUE TITLE
setup-go should install non-git VCS binaries

### ISSUE THREAD

**Issue by mark-rushakoff** [actions/setup-go#18]
My project has a transitive test dependency on a bzr repo or two. It's been a continual source of annoyance, and I haven't been able to find a workaround so that developers can just use Go out of the box without installing bzr.

After invoking setup-go, and calling a `go run` command, I see the following error:

```
  > [line 0 : column 0] - loading files from package ".": go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: bzr branch --use-existing-dir https://launchpad.net/mgo/v2 . in /home/runner/go/pkg/mod/cache/vcs/ca61c737a32b1e09a0919e15375f9c2b6aa09860cc097f1333b3c3d29e040ea8: exec: "bzr": executable file not found in $PATH
 go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /home/runner/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: error loading module requirements
```

Specifically, the `exec: "bzr": executable file not found in $PATH` piece indicates that `bzr` is unavailable.

According to `go help importpath` on go 1.12:

> The vcs is one of "bzr", "fossil", "git", "hg", "svn".

I don't have any dependencies on fossil, hg, or svn, so I don't know whether they're available.

My redacted workflow file looks like:

```
on: push

jobs:
  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build and run analyzer
      run: GO111MODULE=on go run example.com/analyzer ./...
```

**Comment by kjk** [comment]
If you use Go 1.12+ you can use module proxy. Set GOPROXY env variable to https://proxy.golang.org. On 1.13 you don't even have to do that as it's the default.

Here's a full example: https://onepage.nopub.io/p/Using-GitHub-Actions-with-Go-2ca9744b531f4f21bdae9976d1ccbb58#49a308c7-e5de-4c3d-85f0-c319464a0969

**Comment by damccorm** [comment]
Yeah, this doesn't really feel like a mainline use case to me, I'm pretty skeptical of installing things that most users aren't going to need. If you need this it should probably be installed in its own separate action.

**Comment by mark-rushakoff** [comment]
As-is, `go get` doesn't work out of the box in cases where it seems like it should.

As a concrete example, influxdb has an unfortunate dependency chain where a test package depends on a Bazaar package:

```
$ go mod why -m launchpad.net/gocheck
github.com/influxdata/influxdb/nats
github.com/nats-io/nats-streaming-server/server
github.com/hashicorp/go-msgpack/codec
github.com/hashicorp/go-msgpack/codec.test
labix.org/v2/mgo/bson
labix.org/v2/mgo/bson.test
launchpad.net/gocheck
```

[github.com/hashicorp/go-msgpack/codec is imported by several hundred packages](https://godoc.org/github.com/hashicorp/go-msgpack/codec?importers), so although it's not something _everyone_ is going to hit, it's surprisingly common.

You wouldn't think `go run` would fail for being unable to get a dependency of a third party's test package, but unfortunately it does.

If you won't install bzr et al out of the box, please consider documenting the available workarounds. For now, I've added `sudo apt-get install bzr && go run ...`, which I assume isn't the idiomatic Actions way of installing a separate binary.

**Comment by damccorm** [comment]
> which I assume isn't the idiomatic Actions way of installing a separate binary.

That's actually fine IMO - in general we have the setup actions to do things like that in a cross-platform way, but if you don't need the windows build then apt-get should be ok.

> If you won't install bzr et al out of the box, please consider documenting the available workarounds.

I think I'm still skeptical that this should be a responsibility of this repo/I'm not sure if we should be doing this here. As far as I am thinking about this, the issue here is caused by the fact that you're actually taking on 2 dependencies - 1 on Go and 1 on Bzr. This repo guarantees that it will satisfy the first dependency, but I think we should draw the scope line there. If there's sufficient demand for a tool like Bzr then we (or someone else) should build a Bzr action, but I don't think docs about a 3rd party (fairly rare) tool should live here.

If this is truly a dependency of Go (which I don't consider it to be), then the right solution is for it to be bundled with the Go package.

**Comment by bryanmacfarlane** [comment]
I don't think this should be the responsibility of this action.  This action is responsible for pulling go install pkg, adding it to the path and setting up problem matchers.  I also agree with @kjk
