### ISSUE TITLE
Race detector *.syso files missing for cross-compilation

### ISSUE THREAD

**Issue by tamird** [actions/setup-go#181]
This is roughly https://github.com/golang/go/issues/42382.

My understanding is that binaries downloaded from https://github.com/actions/go-versions are *built from source*, rather than being downloaded from https://go.dev/dl/. But apparently not:
```
tamird@tamird:~/src/goid/go$ curl -sfSL https://github.com/actions/go-versions/releases/download/1.17.5-1559554870/go-1.17.5-linux-x64.tar.gz | tar zx
tamird@tamird:~/src/goid/go$ find src/runtime -name '*.syso'
src/runtime/race/race_linux_amd64.syso
```

The official Go binaries have long omitted these files for non-host platforms (https://go-review.googlesource.com/c/build/+/144281/) but that shouldn't have affected go-versions if those packages are indeed built from source. But they appear not to be. It would be nice to fix that so that cross-compilation of race binaries works.

**Comment by vsafonkin** [comment]
Hi @tamird, thank you for your report, we will take a look it.

**Comment by vsafonkin** [comment]
@tamird, sorry for the delay, is this issue still actual for you?

**Comment by tamird** [comment]
I included reproduction instructions in the description. Can you try them?

**Comment by vsafonkin** [comment]
> I included reproduction instructions in the description. Can you try them?

Sure, thank you!

**Comment by vsafonkin** [comment]
@tamird, I'm afraid that building Go from source code will cause a lot of problems and pretty complicated for maintenance. We already have experience with `setup-python` action where we use Python builds from source code for each OS platform and it cause many issues for self-hosted runners.

**Comment by tamird** [comment]
That's fine - it should perhaps be documented how these packages are built.

**Comment by vsafonkin** [comment]
@tamird, I've added a note about it to the readme file, I believe we can close this issue, thank you for your help!
