### ISSUE TITLE
Wrong Go version available in $PATH after installation of the correct version

### ISSUE THREAD

**Issue by xarantolus** [actions/setup-go#200]
**Description:**
The action is asked to install version `^1.17`. It says it installs v1.17.7 (which would be correct), but when actually running a `go` command in a script, the Go version is `1.15.15`. 

This behavior can be seen in [this workflow run](https://github.com/xarantolus/bromite-userscripts/runs/5434312495?check_suite_focus=true): in "Set up Go" it outputs `go version go1.17.7 linux/amd64`, but then in "Run regeneration script" a run of `go version` outputs `go version go1.15.15 linux/amd64`. This leads to build errors in a project that requires packages added in newer Go versions, specifically `embed` and `io/fs`.

What is even more weird is that I added another workflow with the exact same installation steps in the same repository (a different branch: `test-go-action`), and there everything works as expected (see [this run](https://github.com/xarantolus/bromite-userscripts/runs/5434412691?check_suite_focus=true))

**Action version:**
v2 ([see this run](https://github.com/xarantolus/bromite-userscripts/runs/5432089829?check_suite_focus=true)) and v3 ([see this run](https://github.com/xarantolus/bromite-userscripts/runs/5434312495?check_suite_focus=true) - here the script was changed to output the Go version, it outputs `go version go1.15.15 linux/amd64`).

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
It says it installs Go 1.17.7, but the version of the installed `go` tool is 1.15.15.

**Repro steps:**  
I am not entirely sure how to reproduce this issue. It does however happen consistently on [this repository](https://github.com/xarantolus/bromite-userscripts), you can see the [Actions for the `test-go-action` branch](https://github.com/xarantolus/bromite-userscripts/actions?query=branch%3Atest-go-action). "[Test Workflow 1](https://github.com/xarantolus/bromite-userscripts/runs/5434412685?check_suite_focus=true)" outputs `go version go1.15.15 linux/amd64` while "[Test Workflow 2](https://github.com/xarantolus/bromite-userscripts/runs/5434412685?check_suite_focus=true) correctly outputs `go version go1.17.7 linux/amd64`. Both say they installed `go version go1.17.7 linux/amd64` in the "Set up Go" step.

**Expected behavior:**
After installing Go version 1.17.7, the command `go version` should *not* output `go version go1.15.15 linux/amd64` when used in a bash script.

**Actual behavior:**
The command `go version` outputs `go version go1.15.15 linux/amd64` after the installation step says it installed `go version go1.17.7 linux/amd64`.

**Comment by vsafonkin** [comment]
Hi @xarantolus, could you please try this step as workaround after `setup-go` action in your workflow?
```
cp -f `which go` /usr/bin/go
```
This is known issue: #107 
There is symlink to default `go` version on the runner and it can be the problem.

**Comment by xarantolus** [comment]
Thank you, that does indeed appear to change the behavior. Also thank you for linking the issue, seems like I overlooked it :)
