### ISSUE TITLE
README and other documentation are still on v2

### ISSUE THREAD

**Issue by tliron** [actions/setup-go#203]
v3 has been released but the README still references v2. Additionally the input changes for v3 do not seem to be documented.

Furthermore, I think it's important to document how semver matching and ranges work, or at least to provide some examples. There is a lot of confusion among users (see #191).

**Comment by vsafonkin** [comment]
Hi @tliron, I'm going to close this issue cause the docs were updated. Feel free to contact as if you have any questions, thank you!
