### ISSUE TITLE
setup-go is installing go1.17.7 for go 1.17.x whereas go1.17.8 was released a week ago

### ISSUE THREAD

**Issue by ncw** [actions/setup-go#205]
**Description:**

setup-go is installing go1.17.7 for go 1.17.x whereas go1.17.8 was released a week ago.

**Action version:**

actions/setup-go@v2

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

go1.17.x

**Repro steps:**  

This can be seen in the rclone repo here: https://github.com/rclone/rclone/runs/5480156393?check_suite_focus=true

In the "Print Go version and environment" section we see

    Go version: go version go1.17.7 linux/amd64

Wheras we have this in the action yaml

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go }}

Where `matrix.go` is `1.17.x`

Looking at the go downloads we can see there was a security release for go1.17.8

> go1.17.8 (released 2022-03-03) includes a security fix to the regexp/syntax package, as well as bug fixes to the compiler, runtime, the go command, and the crypto/x509, and net packages. See the [Go 1.17.8 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.17.8+label%3ACherryPickApproved) on our issue tracker for details.

Which was 8 days ago now.

**Expected behavior:**

I would have expected go1.17.8 to be used

**Actual behavior:**

go1.17.7 was used

**Discussion.**

The ultimate cause of this seems to be the actions failing in the `actions/go-versions` repositiory.

https://github.com/actions/go-versions/actions/runs/1958001436

That repo doesn't accept bug reports, so I reported it here https://github.com/actions/virtual-environments/issues/5202 as instructed, however it appears no-one has seen that report so I'm posting it here too where it seems more relevant.

**Comment by uynap** [comment]
I'm having the same version. Can someone response to it please?

**Comment by brcrista** [comment]
Ack, we're having a look

**Comment by ethanchewy** [comment]
We pushed a [fix](https://github.com/actions/go-versions/commit/34306dce783b0bb619eea21b8cc99e5d70682bef) recently that fixes this. All recent versions of go should be here https://github.com/actions/go-versions/releases now. Here is an example of a [successful run](https://github.com/ethanchewy/test-go-version/runs/5562384745?check_suite_focus=true).

Thanks for opening this issue and bringing this to our attention @ncw.

**Comment by l3v11** [comment]
> We pushed a [fix](https://github.com/actions/go-versions/commit/34306dce783b0bb619eea21b8cc99e5d70682bef) recently that fixes this. All recent versions of go should be here https://github.com/actions/go-versions/releases now. Here is an example of a [successful run](https://github.com/ethanchewy/test-go-version/runs/5562384745?check_suite_focus=true).
> 
> Thanks for opening this issue and bringing this to our attention @ncw.

Can you please merge this https://github.com/actions/go-versions/pull/50 too? Not getting latest ones without it.

**Comment by brcrista** [comment]
Thanks @l3v11, I merged that PR and tested to make sure it works now.  Note that you'll have to use `check-latest: true` until the next hosted image update goes out.

**Comment by ncw** [comment]
It is working now with `check-latest: true` - thank you all :-)
