### ISSUE TITLE
Feature Request: Use latest stable version

### ISSUE THREAD

**Issue by firefart** [actions/setup-go#219]
**Description:**
It would be nice to supply `stable` to the `go-version` parameter and it would use the latest stable release from the manifest

**Justification:**
Github Action Runners are not always on the latest go version and I want to test my master branch against the latest stable release. Currently this involves changing a lot of repos once a new version comes out so they reference the latest version.

**Comment by IvanZosimov** [comment]
Hi, @firefart 👋 ! `Setup-go` action already has the [feature](https://github.com/actions/setup-go#check-latest-version) that allows you to use the latest stable release of the GO from the [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json) file which is updated  by us frequently. For instance, If you'd like to get the latest patch versions of GO 1.17, you can use `check-latest` input along with typical semver range notation (e.g. using caret): 

```steps:
- uses: actions/checkout@v3
- uses: IvanZosimov/setup-go@v3
  with: 
     go-version: ^1.17
     check-latest: true

**Comment by nadoo** [comment]
The [versions-manifest.json](https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json) still doesn't  have Go1.18.1(released 2022-04-12) in it.

**Comment by IvanZosimov** [comment]
Hi, @firefart 👋 ! Yes, it will switch to 1.18.0 automatically, then when 1.18.1 is available in our [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json) it will switch to 1.18.1 an so on. It happens because by specifying go version using the caret symbol (e.g. ^1.17), we specify this range of the versions ( >=1.17 <2.0.0 ), check [semver documentation](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) for more information about range syntax.

Thank you for your feedback regarding our documentation, we will improve it in order to make it more clear 😊

**Comment by IvanZosimov** [comment]
Hi, @nadoo 👋 ! Thanks a lot for your comment, currently we are working on adding new versions to the [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json).

**Comment by cristaloleg** [comment]
Oh, that's great, thank you @IvanZosimov . As I understand `^1.17` and `check_latest: true` will have the same behaviour, right? (https://github.com/actions/setup-go#check-latest-version)

**Comment by vsafonkin** [comment]
@cristaloleg, not exact, `^1.17` - install version from the pre-installed versions on the runner, for example the latest go version on the Ubuntu 20.04 runner is 1.18: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#go

`check_latest: true` - install version from [go-versions](https://github.com/actions/go-versions/blob/main/versions-manifest.json) repository, the latest available version is 1.18.1 there: https://github.com/actions/go-versions/blob/main/versions-manifest.json

**Comment by akshayjshah** [comment]
Many Go projects have a support policy that mirrors the Go project itself: they support the latest stable release and the prior release. As far as I know, it's not possible to express this policy in `setup-go` config without explicitly listing and updating version numbers.

A few years ago, @abhinav added support for `oldstable` as a version identifier to Travis CI's `gimme`: https://github.com/travis-ci/gimme/pull/170. Something similar here would be very, very nice.

**Comment by IvanZosimov** [comment]
Hi, @akshayjshah 👋 Thank you, that's a very interesting suggestion! Could you please create an additional feature request issue in this repo?
