### ISSUE TITLE
Causing "##[error]No such file or directory" for later "run" steps

### ISSUE THREAD

**Issue by yousong** [actions/setup-go#22]
Hi, the issue was originally reported to GitHub Developer Support and was recommended opening an issue inside "setup-go".  Though from the checks output I cannot see how it's related to setup-go.

Original report

> Hi, I just tried GitHub Action for a repo of mine. It seems I hit a bug.
> 
> When I specify more than 2 "run" steps for a job, only the 1st can run, the 2nd and later ones all fail right away with "##[error]No such file or directory", no other trace were printed even with "set -o xtrace"
> 
> You can find the scene at https://github.com/yousong/pkg/pull/1/checks . The later "run" steps were configured with "continue-on-error" just to check if it will fail for the 3rd run.
> 
> Thank you.

The reply

> Thanks for getting in touch! This looks like it may be an issue with the setup-go action itself. I'd recommend opening an issue inside this repository for more help with this.
>
> https://github.com/actions/setup-go

**Comment by yousong** [comment]
Tried v1 and v1.1.1, the issue persists

**Comment by yousong** [comment]
Friendly ping

**Comment by bryanmacfarlane** [comment]
Doesn't seem like a setup-go issue but @thboop can have a look.

**Comment by thboop** [comment]
Hey @yousong We have an item open for this issue here: https://github.com/actions/runner/issues/169

You can workaround it by separating out the multi-line step into individual steps, as it appears you have done in your repo!

**Comment by yousong** [comment]
> Hey @yousong We have an item open for this issue here: [actions/runner#169](https://github.com/actions/runner/issues/169)

Note sure if it's because of redirection, but definitely it's not powershell.  So likely the issue is different.

> 
> You can workaround it by separating out the multi-line step into individual steps, as it appears you have done in your repo!

I compacted all shell run steps into into a single one.  Not split them into individual steps.

Note that the issue is reported here is that 2nd and later shell run steps fail

**Comment by thboop** [comment]
Hey @yousong , I apologize I misread your issue.

I forked your repo and was able to reproduce the issue!

The runner is actually throwing an error because the folder it expects to find is missing. If you change your line [here](https://github.com/yousong/pkg/commit/c51b455ec8a23cbbd500c0f6d1446cef0a0f1ee5#diff-b656efd19fb97cae3ade48f6991e96efR27) to `cp -r` instead of `mv` the following steps should execute.

You can see my example [here](https://github.com/thboop/pkg/blob/a/.github/workflows/build-and-test.yaml#L21)

That being said, if you don't need to use that directory for your workflow to work, you may want to consider using the current working directory to slightly speed up your actions!

**Comment by yousong** [comment]
> Hey @yousong , I apologize I misread your issue.
> 
> I forked your repo and was able to reproduce the issue!
> 
> The runner is actually throwing an error because the folder it expects to find is missing. If you change your line [here](https://github.com/yousong/pkg/commit/c51b455ec8a23cbbd500c0f6d1446cef0a0f1ee5#diff-b656efd19fb97cae3ade48f6991e96efR27) to `cp -r` instead of `mv` the following steps should execute.
> 
> You can see my example [here](https://github.com/thboop/pkg/blob/a/.github/workflows/build-and-test.yaml#L21)

I see.  It's working directory "not found" because I moved it to another place.

> 
> That being said, if you don't need to use that directory for your workflow to work, you may want to consider using the current working directory to slightly speed up your actions!

This is specific to the golang code and the container image in use here.  The code needs to sit in `$GOPATH` and we tend to set it to `$HOME/go`.  `$GOPATH` has its own directory structure.

Anyway, thanks for your time and efforts.  Appreciate it

Good day ;)
