### ISSUE TITLE
"x509: certificate signed by unknown authority" when used in a container

### ISSUE THREAD

**Issue by trinitroglycerin** [actions/setup-go#220]
**Description:**
This is a similar bug to #110, which was closed due to inactivity. A trivial setup results in an SSL error when attempting to pull a public Go package located on Github. This occurs when using the [nekros/act](https://github.com/nektos/act) tool to test the Workflow locally, and so this may be an issue that lies with the default runner that that tool provides.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

This is running on Ubuntu through WSL on Windows.

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
`go version go1.18 linux/amd64`

**Repro steps:**  
```
$ go install github.com/nektos/act@latest
$ mkdir -p .github/workflows
$ echo <<EOF
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - run: go get
EOF >> .github/workflows/
$ echo <<EOF
module example.com/my-module

require (
	github.com/RobotsAndPencils/go-saml v0.0.0-20170520135329-fb13cb52a46b
)
EOF >> go.mod
$ act
```

**Expected behavior:**
Go dependencies to be downloaded into the container.

**Actual behavior:**
Go encounters an SSL error when attempting to download the first dependency in the go.mod:

```
go: github.com/RobotsAndPencils/go-saml@v0.0.0-20170520135329-fb13cb52a46b: Get "https://proxy.golang.org/github.com/%21robots%21and%21pencils/go-saml/@v/v0.0.0-20170520135329-fb13cb52a46b.mod": x509: certificate signed by unknown authority
```

**Comment by vsafonkin** [comment]
Hi @trinitroglycerin, thank you for your report, we will take a look at this.

**Comment by trinitroglycerin** [comment]
No worries. You can find the repository I am using here - note that this works just fine when hosted on Github itself. [github.com/trinitroglycerin/key-conjurer](https://github.com/trinitroglycerin/key-conjurer/tree/workflow)

**Comment by mckern** [comment]
I also ran into this problem building in an `ubuntu:22.10` container. I needed to make sure that `ca-certificates` were installed before trying to fetch my dependencies:

```
$ apt-get update && apt-get install -y --no-install-recommends ca-certificates
```

**Comment by IvanZosimov** [comment]
Hello, @trinitroglycerin and @mckern  👋 Thank you for your comments! It seems that the root of this problem is not in our action, but as it was written above in a lack of CA certificates on the runner. Go tries to download dependencies but basically can't confirm the validity of the server's certificate without CA certificates installed. 

As a workaround, you can use the approach that @mckern described (install or update missing CA certificates either by hand or incorporate that inside the workflow).

**Comment by IvanZosimov** [comment]
📟 Just a gentle ping, @trinitroglycerin . We are closing this issue right now, if you have any questions or additions feel free to ping us.
