### ISSUE TITLE
Add an alias for the previous stable Go release

### ISSUE THREAD

**Issue by akshayjshah** [actions/setup-go#232]
**Description:**
I'd like `setup-go` to support `stable` and `oldstable` as Go version identifiers. `stable` would resolve to the latest patch release of the current stable minor release (so `1.18.x` today), and `oldstable` would resolve to the latest patch release of the _previous_ minor release (so `1.17.x` today). These aliases make it easy for projects to offer the same support policy as the Go language.

**Justification:**
With semver ranges, it's easy to express "use the latest Go release": `^1.18.1` works. However, this is an awkward approach for Go projects:

* Go doesn't use this style of semantic versioning for dependency management, so the syntax is unfamiliar to much of the target audience.
* Many projects mirror [Go's own support policy](https://go.dev/doc/devel/release#policy) and want to test on both `stable` and `oldstable`. Expressing this today requires changing the workflow definition every 6 months.
* Travis CI's `gimme` has supported this for years, starting with https://github.com/travis-ci/gimme/pull/170 from @abhinav.

I'm not attached to the `stable` and `oldstable` names in particular (I think Travis CI wanted `oldstable` because it's similar to a Debian convention) - happy to use whatever you'd like.

**Are you willing to submit a PR?**
Happy to.

**Comment by akshayjshah** [comment]
Any updates, @IvanZosimov?

**Comment by panticmilos** [comment]
Hi @akshayjshah,

Sorry for late response. For now, this feature is not in our plans. :( You can provide a PR with this functionality, we will review it and discuss it further more if that's the case.

**Comment by akshayjshah** [comment]
Sure, happy to put up a PR.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've released [v3.5.0](https://github.com/actions/setup-go/releases/tag/v3.5.0) and updated the major tag with aliases. Could you please confirm that it works as expected ?

**Comment by panticmilos** [comment]
hi @akshayjshah, we have released this feature, as @dmitry-shibanov mentioned, in the [v3.5.0](https://github.com/actions/setup-go/releases/tag/v3.5.0). 

I will close this issue for now, but when you get a chance to test if there is any issue, please feel free to reopen this issue, or create a new one.

**Comment by akshayjshah** [comment]
Works as expected - thanks for implementing and releasing this! 😻
