### ISSUE TITLE
go binary CPU compatibility

### ISSUE THREAD

**Issue by chris-sneller** [actions/setup-go#233]
Sometimes the Github Workflow errors with: 

"This program can only be run on AMD64 processors with v4 microarchitecture support."

when trying to compile with "go build"

It happens around 1/3 of the time.  

I'm using:

**Platform:**
- [ ] Ubuntu
- [ ] 
**Runner type:**
- [ ] Hosted

**Tools version:**
1.18.1

**Repro steps:**  
runs-on: ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.1"

and run "go bulid"

**Expected behavior:**
A more portable binary be installed

**Actual behavior:**
One build for "v4 microarchetecture" is installed.

**Comment by Aruto7709p** [comment]
@jclem

**Comment by dmitry-shibanov** [comment]
Hello @chris-sneller. Thank you for your report. Could you please provide link to the public repository to reproduce the issue?

**Comment by chris-sneller** [comment]
No, it's not public.

**Comment by IvanZosimov** [comment]
Hello, @chris-sneller 👋 Thank you for this issue! The thing is that our hosted runners are using this [row](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) of CPUs. Some of them do support AMD64 v4 architecture and some of them don't. As we can't guarantee that each run of your workflow will be done on the proper runner for your needs, I can suggest a workaround here:
1. If it doesn't matter to you what architecture the Go compiler uses, try to push it to use v3 architecture by setting the Go env variable `GOAMD64` as `v3` before building your application.
2. If you deliberately want to use AMD64 v4 architecture, you can set up your own [self-hosted](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) runner with a CPU that supports this architecture. 

Cheers!

**Comment by IvanZosimov** [comment]
📟 Just a gentle ping, @chris-sneller. We are closing this issue right now, if you have any questions or additions feel free to ping us.

**Comment by chris-sneller** [comment]
It turns out I was setting v4 elsewhere.  I may have misunderstood that it was the go binary rather than the resulting binary that was giving the error.
