### ISSUE TITLE
Go Build indicates insufficient permission

### ISSUE THREAD

**Issue by jiangxiaobao** [actions/setup-go#234]
This is my workflows:
![image](https://user-images.githubusercontent.com/104970147/167815926-d1d51e04-5aaa-45de-b141-16216a58787a.png)

Download private repository dependency error：
![image](https://user-images.githubusercontent.com/104970147/167816325-c3d78215-949c-4ff6-8668-f7b706754dd3.png)

**Comment by dmitry-shibanov** [comment]
Hello @jiangxiaobao. Thank you for your report. Could you please fill out the form ? Do you download private repository from your account or other organisation ?
