### ISSUE TITLE
Install on Windows is very slow

### ISSUE THREAD

**Issue by G-Rath** [actions/setup-go#240]
**Description:**
Installing Go on Windows seems to consistently take at least 30+ seconds to install, usually 1 minute and sometimes more - it's at least consistently 30 seconds longer than on other OSs (which typically take 10-20 seconds).

This consistently represents ~3/4th of the CI run time for [`osv-detector`](https://github.com/G-Rath/osv-detector) - the test suite takes only ~20 seconds (on Windows).

![image](https://user-images.githubusercontent.com/3151613/175659615-72af83e8-d05a-40a9-852c-8d430af2cf66.png)

![image](https://user-images.githubusercontent.com/3151613/175659635-c8e74b7b-a939-4f43-9106-5bc713d77cff.png)

https://github.com/G-Rath/osv-detector/runs/7033093878?check_suite_focus=true

This one took 3 minutes:

https://github.com/G-Rath/osv-detector/runs/7033278935?check_suite_focus=true

**Action version:**
v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

1.17.9

**Repro steps:**  
https://github.com/G-Rath/osv-detector/blob/main/.github/workflows/checks.yml

https://github.com/G-Rath/osv-detector/actions/workflows/checks.yml
https://github.com/G-Rath/osv-detector/runs/7033093878?check_suite_focus=true
https://github.com/G-Rath/osv-detector/runs/7034205194?check_suite_focus=true
https://github.com/G-Rath/osv-detector/runs/7033293623?check_suite_focus=true
https://github.com/G-Rath/osv-detector/runs/7033278935?check_suite_focus=true

**Expected behavior:**
The install time to be below 30 seconds on average, ideally never going over a minute.

**Actual behavior:**
The install time is consistently above 30 seconds, often even above 1 minute and sometimes as long as 3 minutes.

**Comment by dmitry-shibanov** [comment]
Hello @G-Rath. Thank you for your report. We'll investigate the issue.

**Comment by panticmilos** [comment]
Hi @G-Rath,

We need to replace extracting method in order to fix this issue. I will let you know when that PR is ready.

**Comment by ValentinTrinque** [comment]
Is this something that is still planned ?

On one of my setup:
- Linux takes ~20s
- MacOS is a bit slower and takes ~1m
- But Windows takes ~3m20s

<img width="1067" alt="Screenshot 2023-04-04 at 12 24 11" src="https://user-images.githubusercontent.com/4662842/229763519-bca9a10f-01b7-425b-9115-a3ce81b1a67d.png">


Not sure if this can help, the problem has been seen on windows there:
- https://github.com/microsoft/Windows-Dev-Performance/issues/27

**Comment by KyleSanderson** [comment]
Any update on this very simple issue? All of the time is taken in zstd.

**Comment by dsame** [comment]
It does not seem we can solve the issue. The problem always relates to the writing to c: drive and it seems there's some IO issue. I'll try to escalate the problem either to hardware team or toolcache team with the question is it possible to move hostedtoolcache folder to the D: drive

unpacking  c: to c: https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9376098775#step:3:209 **~3min**
copy c: to c:  https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9376098775#step:3:215 **~20sec**

unpacking  c: to d: https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9374998056#step:3:209 **~5sec**
copy d: to c: https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9374998056#step:3:216 **~1m10sec**

 the same 2 https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9374998877#step:3:209
 
unpacking  d: to d:  https://github.com/akv-demo/test-setup-go/actions/runs/5198627779/jobs/9374998877#step:3:209 **3sec**
copy d: to c:  https://github.com/akv-demo/test-setup-go/actions/runs/5197317747/jobs/9373658802#step:3:215 **~50sec**

the same https://github.com/akv-demo/test-setup-go/actions/runs/5197317747/jobs/9373659211#step:3:208

**Comment by KyleSanderson** [comment]
@dsame none of those runs are public so I can't see what you've tried unfortunately.

Has anyone looked into the 15 yearold dism? It sound give 0 second loading, and an optimized compression format on commit. imagex is older, and while I remember it to be slower, I'm unclear on any optimizations that have happened to this even older technology.

**Comment by dsame** [comment]
@KyleSanderson i made the repo public, but  there's no sense to waste your time looking into it. The problem is confirmed, the fix is suggested and the issue is expected to be solved in the next 4-5 weeks.

**Comment by MatthewRyanRead** [comment]
Please consider #515 as well; it looks like it would save me about 5 minutes, and the PR author about 10!
