### ISSUE TITLE
Support BoringCrypto distributions of Go

### ISSUE THREAD

**Issue by davidsbond** [actions/setup-go#243]
**Description:**
The current versions of go supported are strictly the binaries released with Go's own crypto packages. These packages are not FIPS compliant so for a FIPS compliant build you need to use the [separate binary releases that use BoringCrypto](https://github.com/golang/go/blob/dev.boringcrypto.go1.18/misc/boring/README.md). These binaries are made available at `https://go-boringcrypto.storage.googleapis.com/`. 

Right now, the `go-versions` manifest doesn't include these, but could save people aiming for FIPS complaint builds some time by also supporting them. When it comes to the github action, the desired change would manifest like so:

```yaml
steps:
  - uses: actions/setup-go@v3
    with:
      go-version: 1.8.3b3
  - run: go version
```

The inclusion of the `b(n)` after the version indicates it is the BoringCrypto version. 

**Justification:**

Many open-source projects aim to get FIPS compliance. If this action supports setting up the FIPS-compliant go versions then we're saving those users implementing their own method of installing go from the alternative source. 

**Are you willing to submit a PR?**

I'd be willing to give it a go, although I'm not too familiar with PowerShell which the go-versions scripts seem to use.

**Comment by marko-zivic-93** [comment]
Hello @davidsbond 
Thank you for your report. We will investigate this and come back to you as soon as we have some information :)

**Comment by davidsbond** [comment]
Hey @panticmilos, I could give it a try. It seems like [here](https://github.com/actions/versions-package-tools/blob/6f1aa3ce73ce0ea4b58995a63b56a8677607762a/get-new-tool-versions/parsers/go-parser.psm1#L10) is where the magic lives. Although I've never written any PowerShell.

**Comment by dayananda30** [comment]
Upvoting for this feature request.

**Comment by davidsbond** [comment]
I've started trying to write some sort of powershell script to parse and do something with the list of files in that bucket. Unfortunately, it's not as easy to use as the one for vanilla golang. Here's what I'm playing with so far:

```powershell
$url = "https://go-boringcrypto.storage.googleapis.com"
$response = Invoke-RestMethod $url
$releases = $response.ListBucketResult.Contents.Key
echo $releases
```

This is outputting every key in the bucket. This includes a lot of noise as there's source archives & binaries all together. I think we would be able to infer things like the os/arch based on the filenames, but I'm essentially learning powershell here so could take some time. If anyone knows powershell a bit better it might be easier.

**Comment by dayananda30** [comment]
@davidsbond, even I am new to powershell but I can help you.
How do we have to parse response output? Do you have expected output after the parse? I can look into it parallelly:-)

**Comment by davidsbond** [comment]
Thanks @dayananda30. It seems to start with we need to include the available versions for the boring crypto binaries when they are returned in [this function](https://github.com/actions/versions-package-tools/blob/main/get-new-tool-versions/parsers/go-parser.psm1#L10).

This is where I am starting from, although there's probably a few more places to change things

**Comment by davidsbond** [comment]
```powershell
$url = "https://go-boringcrypto.storage.googleapis.com"
$response = Invoke-RestMethod $url
$items = $response.ListBucketResult.Contents
$binaries = $items | Where-Object -Property Key -Match '^((?!src).)*$'
$binaries = $binaries | Where-Object -Property Key -Match '^((?!boringcrypto).)*$'
echo $binaries.Key
```

This seems to give me a list of just the binaries, No idea how to parse this further currently:

```
go1.17.10b7.linux-amd64.tar.gz
go1.17.11b7.linux-amd64.tar.gz
go1.17.12b7.linux-amd64.tar.gz
go1.17.2b7.linux-amd64.tar.gz
go1.17.3b7.linux-amd64.tar.gz
go1.17.4b7.linux-amd64.tar.gz
go1.17.5b7.linux-amd64.tar.gz
go1.17.6b7.linux-amd64.tar.gz
go1.17.7b7.linux-amd64.tar.gz
go1.17.8b7.linux-amd64.tar.gz
go1.17.9b7.linux-amd64.tar.gz
go1.18.1b7.linux-amd64.tar.gz
go1.18.2b7.linux-amd64.tar.gz
go1.18.3b7.linux-amd64.tar.gz
go1.18.4b7.linux-amd64.tar.gz
go1.18b7.linux-amd64.tar.gz
go1.8.3b3.linux-amd64.tar.gz
go1.8.3b4.linux-amd64.tar.gz
go1.9.2b4.linux-amd64.tar.gz
go1.9.3b4.linux-amd64.tar.gz
go1.9.4b4.linux-amd64.tar.gz
go1.9.7b4.linux-amd64.tar.gz
go1.9b4.linux-amd64.tar.gz
go1.9rc2b2.linux-amd64.tar.gz
go1.9rc2b4.linux-amd64.tar.gz
...
```

**Comment by davidsbond** [comment]
Where we want to get to is including these binaries in the [go-versions manifest](https://github.com/actions/go-versions/blob/main/versions-manifest.json) (following the same format) which is used by this action.

It's slightly easier perhaps, as the os/arch will always be linux/amd64.

**Comment by dayananda30** [comment]
@davidsbond , 
echo $response.ListBucketResult.Contents.Key
go1.10.3b4.linux-amd64.tar.gz
go1.10.3b4.src.tar.gz
go1.10.4b4.linux-amd64.tar.gz
go1.10.4b4.src.tar.gz
go1.10.7b4.linux-amd64.tar.gz
go1.10.7b4.src.tar.gz
go1.10.8b4.linux-amd64.tar.gz
go1.10.8b4.src.tar.gz
go1.10rc2b4.linux-amd64.tar.gz
go1.10rc2b4.src.tar.gz
go1.11.11b4.linux-amd64.tar.gz
go1.11.11b4.src.tar.gz
go1.11.12b4.linux-amd64.tar.gz
go1.11.12b4.src.tar.gz
go1.11.13b4.linux-amd64.tar.gz
go1.11.13b4.src.tar.gz
go1.11.2b4.linux-amd64.tar.gz

**Comment by dayananda30** [comment]
> Where we want to get to is including these binaries in the [go-versions manifest](https://github.com/actions/go-versions/blob/main/versions-manifest.json) (following the same format) which is used by this action.
> 
> It's slightly easier perhaps, as the os/arch will always be linux/amd64.

@davidsbond , looks, like we need to add it for all the BoringCrypto go distributions.
let me know, you need to my help in adding them.

**Comment by dayananda30** [comment]
@davidsbond 
**Foreach ($item in $releases) { $go_versions=[System.IO.Path]::GetFileNameWithoutExtension($item) -Split(".tar"); $go_versions.Split('',[System.StringSplitOptions]::RemoveEmptyEntries) }**

This trims off .tar.gz extensions and returns the array with only names without extensions

**Comment by reedloden** [comment]
Isn't this easier now with Go 1.19? You should be able to use `GOEXPERIMENT=boringcrypto`.

**Comment by panticmilos** [comment]
hi @reedloden, thank you for your input on this topic. I saw this flag as well, @davidsbond and @dayananda30 could you confirm this solution is valid for you?

**Comment by davidsbond** [comment]
Yeah doing that is fine by me, not sure if there are people using sub 1.19 version that would still want this but I'm happy to close and use that environment variable. I haven't really had the time or knowledge to dive deep into how to achieve this and open a PR.

**Comment by panticmilos** [comment]
Hi @davidsbond, I am going to close it for now, but if you have any additional questions feel free to reopen it or continue conversation here.
