### ISSUE TITLE
Use go.dev/dl registry to get Go binaries

### ISSUE THREAD

**Issue by 0xch4z** [actions/setup-go#247]
**Description:**
Use the officially supported release channel, go.dev/dl. It's more up to date with the latest builds.

**Justification:**
I wanted to use this action with go1.19rc.1 but the storage.googleapis.com registry is not up to date.

**Are you willing to submit a PR?**
Yes

**Comment by marko-zivic-93** [comment]
Hello @0xch4z 
Thank you for your feedback. We will investigate this issue as soon as possible and come back to you with some info :)

**Comment by e-korolevskii** [comment]
Hi @0xch4z!
After our investigation, we were unable to find version inconsistencies. Could you please provide an example of a workflow with an error?

**Comment by 0xch4z** [comment]
From the issue description:
> I wanted to use this action with go1.19rc.1 but the storage.googleapis.com registry is not up to date.

It was 2+ weeks ago when the builds were behind. Besides I'm not sure if there ever was a reason not to use the official release channel that the Go team uses.

**Comment by e-korolevskii** [comment]
Hello @0xch4z 

Since we have not been able to find differences in the currently available versions of these resources, we do not see the benefit of changing the source.
