### ISSUE TITLE
Issues with cache option post step.

### ISSUE THREAD

**Issue by schmidtw** [actions/setup-go#258]
**Post Setup Error: There are no cache folders on the disk**

Here is an [example run](https://github.com/xmidt-org/medley/runs/8119220265?check_suite_focus=true) showing the problem I'm encountering.  The action flow runs fine, but for some reason during the `Post Setup go version` part of the step an error is indicated flagging the workflow to fail.

**Action version:**
actions/setup-go@v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
It's unclear why this happens sometimes and not others.

**Expected behavior:**
No error if nothing was cached.

**Actual behavior:**
An error is raised, failing the workflow.

**Comment by e-korolevskii** [comment]
Hello @schmidtw! 

Thank you for your report. We'll investigate the issue.

**Comment by e-korolevskii** [comment]
Hello @schmidtw!

After investigation, we decided that the absence of cache folders should not lead to an error. We have already made the necessary [changes to the code](https://github.com/actions/setup-go/pull/264), but you should wait for the release of the new version.
For now, you can disable cache usage to get rid of this error.
