### ISSUE TITLE
Error messages not really usable.  missing line breaks

### ISSUE THREAD

**Issue by TimSatke** [actions/setup-go#26]
![image](https://user-images.githubusercontent.com/48135919/68077825-13917900-fdcb-11e9-9659-5fb6a97b4f2e.png)

My error messages look like this. Is this a configuration issue of mine?

If not, can this be improved?
The line break bytes are there and get copied if I do, but in this view, it is very hard to use.

**Comment by thboop** [comment]
Hey @TimSatke are you still encountering this issue?

If so, could you provide a link to your log or steps to reproduce?

**Comment by TimSatke** [comment]
Yes I am, it is the output in the actions console. It is only commented and formatted on pull requests, not on pushes. 
See e.g. failing lint jobs in tomarrell/lbadd or gojisvm/gojis

**Comment by bryanmacfarlane** [comment]
@thboop ping for follow up

**Comment by bryanmacfarlane** [comment]
@TimSatke - can you provide the block of text from your log that led to the problematic annotation?  (feel free to change file names etc)

I have this PR and I would to see if it addresses your exact problem:
https://github.com/actions/setup-go/pull/48

**Comment by TimSatke** [comment]
This is the text from the log. It doesn’t lead to a problematic annotation, in fact, annotations work. However, if there is no pull request, but the action runs on a normal commit, this wall of text is the only thing that can help me, and there is no annotation at all.

**Comment by bryanmacfarlane** [comment]
Thanks.  So it seems like the line breaks not being honored is the root issue in this case?

> The line break bytes are there and get copied if I do, but in this view, it is very hard to use.

And that leads to a wall of text.  Not sure how pull request vs normal commit would influence.

I'm going to check with some runner folks.

**Comment by ericsciple** [comment]
I downloaded the logs for [this job](https://github.com/tomarrell/lbadd/runs/537111329?check_suite_focus=true) and using a hex editor it appears to be a space `0x20` not a line feed `0x0A`.

<img width="670" alt="Screen Shot 2020-03-30 at 7 22 06 PM" src="https://user-images.githubusercontent.com/12102068/77971471-c9022300-72bc-11ea-99b7-cbb0d6474a3b.png">

I see the step uses the container action `grandcolline/golang-github-actions@v1.1.0`. You might check with that action author whether they are capturing the output from the compiler and mutating before writing back to STDOUT.

I have never heard of the runner squashing line feeds. My best guess - if the compiler is indeed outputting line feeds? - then some other process is in the middle.

**Comment by bryanmacfarlane** [comment]
Thanks @ericsciple !

**Comment by TimSatke** [comment]
Has this been resolved?
