### ISSUE TITLE
Should work without a go.sum file

### ISSUE THREAD

**Issue by codefromthecrypt** [actions/setup-go#266]
**Description:**
Things should be fine without a go.sum file as some projects have no deps

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.16.15

**Repro steps:**  
```yaml
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'
          cache: true
```

**Expected behavior:**
no problemo

**Actual behavior:**

https://github.com/tetratelabs/tinymem/runs/8264698787
```
 Setup go version spec 1.16
Attempting to download 1.16...
matching 1.16...
Acquiring 1.16.15 from https://github.com/actions/go-versions/releases/download/1.16.15-1989287126/go-1.16.15-linux-x64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/3a63868b-0d64-4335-8b8e-944786ae1f5f -f /home/runner/work/_temp/274ba212-6adf-4f47-a4e4-de0659b6cd18
Successfully extracted go to /home/runner/work/_temp/3a63868b-0d64-4335-8b8e-944786ae1f5f
Adding to the cache ...
Successfully cached go to /opt/hostedtoolcache/go/1.16.15/x64
Added go to the path
Successfully set up Go version 1.16
/opt/hostedtoolcache/go/1.16.15/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.16.15/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
```

**Comment by codefromthecrypt** [comment]
note: workaround is to touch and commit a go.sum file

**Comment by e-korolevskii** [comment]
Hello @codefromthecrypt! 

Thank you for your report. We'll investigate the issue.

**Comment by e-korolevskii** [comment]
Hi @codefromthecrypt 

According to the [docs](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs):
`The default action looks for the go.sum dependency file at the root of the repository and uses its hash as part of the cache key`.
So that's why the error is thrown here because we need a hash for the cache to work.

But you can use some workarounds:
- disable cache
- create file `go.sum`
- use input cache-dependency-path for some files to generate hash

**Comment by codefromthecrypt** [comment]
I created a dummy go.sum file for now. Main thing I wanted to do was boilerplate config so that it is "cache ready" as project often later add deps, and I've noticed winky builds in the last several years where some setup go but don't (remember to) add cache later.
