### ISSUE TITLE
command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by godcong** [actions/setup-go#276]
**Description:**
```docs
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Action version:**
Specify the action version
```docs
actions/setup-go@v3
```

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

1.19.2

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
see my actions:
https://github.com/babyname/fate/actions/workflows/go.yml

**Expected behavior:**
A description of what you expected to happen.
[use new](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
**Actual behavior:**
A description of what is actually happening.
the env setting need update

PS: `setup-go` seems that GOROOT is not set. when i use $GOROOT/bin/go will failed

**Comment by Xunzhuo** [comment]
+1, this needs some updates.

**Comment by marko-zivic-93** [comment]
Hello @godcong 
Thank you for your issue. We will investigate it and come back to you as soon as possible with some news :)

**Comment by reubenmiller** [comment]
The deprecation warning should be removed once the `@actions/core` npm package is updated to `v1.10.0` or later [(see github announcement)](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). 

The `main` branch is already using this version, so it probably not much to do apart from cutting a new release.

**Comment by e-korolevskii** [comment]
Hi @godcong!

Yesterday we released a new version that includes a solution to this issue.
Could you confirm that it is now working as expected?

**Comment by reubenmiller** [comment]
Confirmed (at least for on my project). I just checked the logs and the above warning is now gone when using setup-go. Thanks for the fast response!

**Comment by dmitry-shibanov** [comment]
Thank you for your response @reubenmiller. I'm going to close the issue.
