### ISSUE TITLE
in v3 setup-go does not set GOROOT 

### ISSUE THREAD

**Issue by shoenig** [actions/setup-go#278]
We are running into this after trying to fix the deprecation warnings named in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

As @godcong noted at the bottom of https://github.com/actions/setup-go/issues/276

The setting of `GOROOT` is not happening anymore.
This is breaking builds where we depend on `$GOROOT` being set and on the `$PATH`.

**Comment by shoenig** [comment]
Hi @e-korolevskii , I created this PR against a sample repository just to reproduce this issue

https://github.com/shoenig/setup-go-example/pull/1

We can see in the v1 version, `GOROOT is /opt/hostedtoolcache/go/1.19.1/x64`

And in the v3 version, `GOROOT is ` (empty string)

The part where we set GOBIN=GOROOT/bin is just demonstrating why our builds are failing - we make use of GOROOT/bin as a user writable directory on PATH we can install Go tooling into to perform the build.

**Comment by dmitry-shibanov** [comment]
Hello @shoenig. The `GOROOT` was removed in this pull request. https://github.com/actions/setup-go/pull/175

**Comment by shoenig** [comment]
@dmitry-shibanov what is the suggested workaround, then? We were using that exported environment variable, as it is particularly useful on Windows builders where mangling PATH is tedious.

**Comment by godcong** [comment]
This only leads to some compatibility problems, manually modified on the good.
I upgraded from setup@v1, and at first I thought action failed.
Then I changed all the places that use GOROOT and it was fine

**Comment by shoenig** [comment]
I had a thought - what if `setup-go` automatically exported `GOBIN` to a useful path - one that is writeable by the actions user and is also added to the `$PATH`? 

That's really what we're trying to get at in our use of `$GOROOT/bin`, but doesn't have a problem with multiple Go installations.

**Comment by shoenig** [comment]
In case anyone else runs into this, we created https://github.com/hashicorp/setup-golang to get the behavior we really wanted (export a `GOBIN` on `PATH`)
