### ISSUE TITLE
Dependencies file is not found in /home/runner/work/mysql-parser/mysql-parser. Supported file pattern: go.sum

### ISSUE THREAD

**Issue by chenquan** [actions/setup-go#281]
**Description:**

Dependencies file is not found in /home/runner/work/mysql-parser/mysql-parser. Supported file pattern: go.sum
link:https://github.com/chenquan/mysql-parser/actions/runs/3306781870/jobs/5457927152
![image](https://user-images.githubusercontent.com/20548053/197388249-80d50fff-1038-475f-8355-2d24835e54d8.png)

**Action version:**
actions/setup-go@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @chenquan. Thank you for your report. We'll investigate the issue. As a possible solution you can try to use [cache-dependency-path](https://github.com/actions/setup-go/blob/main/action.yml#L18-L19) to specify path to `go.sum`.

**Comment by chenquan** [comment]
> Hello @chenquan. Thank you for your report. We'll investigate the issue. As a possible solution you can try to use [cache-dependency-path](https://github.com/actions/setup-go/blob/main/action.yml#L18-L19) to specify path to `go.sum`.

Hi~ It still doesn't work when I specify a path.
https://github.com/chenquan/mysql-parser/actions/runs/3306809761/jobs/5457972883

**Comment by chenquan** [comment]
> Hello @chenquan. Thank you for your report. We'll investigate the issue. As a possible solution you can try to use [cache-dependency-path](https://github.com/actions/setup-go/blob/main/action.yml#L18-L19) to specify path to `go.sum`.

Hi~ It still doesn't work when I specify a path.
https://github.com/chenquan/mysql-parser/actions/runs/3306809761/jobs/5457972883

**Comment by dmitry-shibanov** [comment]
Could you please place `actions/checkout` before `actions/setup-go` ?

**Comment by chenquan** [comment]
> Could you please place`actions/checkout`before`actions/setup-go` ?

oh, I ignored the question. Thx

**Comment by chenquan** [comment]
done
