### ISSUE TITLE
[Feature request] add support go.work file for go-version-file

### ISSUE THREAD

**Issue by koba1t** [actions/setup-go#284]
**Description:**
Support [go workspace mode](https://go.dev/ref/mod#workspaces) for [go-version-file](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file).
`go workspace` uses `go.work` file that summarizes packages when the repo contains multiple packages.

**Justification:**
If repo contains multiple go packages with many `go.mod` files, we can't select one `go.mod` file to set `go-version-file`.
So, that case we can use `go workspace` mode and create one `go.work` file to summarize packages.
This "Feature request" wants to select the go version from the `go.work` file to easy to set the go version in CI.

**Are you willing to submit a PR?**

**Comment by marko-zivic-93** [comment]
Hello @koba1t 
Thank you for your feature request. We are looking into it, and will come back to you as soon as we have some information :)

**Comment by e-korolevskii** [comment]
Hello @koba1t 

We just merged this pull request, but we need to wait for the new release to use these changes.
Thanks for your contribution!
