### ISSUE TITLE
Suggestion: Use early return pattern to avoid nested conditions

### ISSUE THREAD

**Issue by jongwooo** [actions/setup-go#297]
## Description

Return early is the way of writing functions or methods so that the expected positive result is returned at the end of the function and the rest of the code terminates the execution (by returning or throwing an exception) when conditions are not met.

See [actions/cache#1012](https://github.com/actions/cache/issues/1012)

In `cache-utils.ts`:

**AS-IS**

```typescript
export function isCacheFeatureAvailable(): boolean {
  if (!cache.isFeatureAvailable()) {
    if (isGhes()) {
      throw new Error(
        'Cache action is only supported on GHES version >= 3.5...'
      );
    } else {
      core.warning(
        'The runner was not able to contact...'
      );
    }

    return false;
  }

  return true;
}
```

**TO-BE**

```typescript
export function isCacheFeatureAvailable(): boolean {
  if (cache.isFeatureAvailable()) {
    return true;
  }

  if (isGhes()) {
    throw new Error(
      'Cache action is only supported on GHES version >= 3.5...'
    );
  }

  core.warning(
    'The runner was not able to contact...'
  );
  return false;
}
```

**Comment by e-korolevskii** [comment]
Hi @jongwooo 

We will investigate this issue and come back to you.

**Comment by e-korolevskii** [comment]
Hi @jongwooo!

Thanks for your contribution!
The changes will be available in the next release. I am closing this issue for now!
