### ISSUE TITLE
Use the latest release

### ISSUE THREAD

**Issue by cristaloleg** [actions/setup-go#31]
#11 gave us the ability to use the latest version for a specific release, in other other words - to care about major and minor, but not a patch version.

Is it possible to specify the latest minor as well? Just a `1.x` which will take the latest Go release, today it will be `1.13.4`, but after the release of `1.14` (somewhere in February) `1.x` become `1.14.x`.

Basically, the same as Travis does. Thank you.

**Comment by bryanmacfarlane** [comment]
v2-beta supports full semver support.  e.g. https://github.com/bryanmacfarlane/actions-playground/blob/master/.github/workflows/tools.yml#L27

v2-beta also supports a stable true / false input.

So all this should be fixed and possible in v2-beta.  Please give it a try.

**Comment by bryanmacfarlane** [comment]
Please let me know if you can't achieve what you're after with v2-beta.  I'll reactivate if not.
