### ISSUE TITLE
'stable' not working

### ISSUE THREAD

**Issue by ldemailly** [actions/setup-go#320]
**Description:**

Switched for working '1.19.4' to 'stable' per doc (to get 1.19.5 now and future versions later) and got

```
Run actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
  with:
    go-version: stable
    check-latest: false
    token: ***
    cache: false
Setup go version spec stable
Attempting to download stable...
matching stable...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version 'stable' for platform linux and architecture x6[4](https://github.com/fortio/proxy/actions/runs/3932404413/jobs/6724921344#step:3:4).
```

**Action version:**

268d8c0ca0432bb2cf416faae41297df9d262d7f

3.5.0+

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  

https://github.com/fortio/proxy/commit/86c973c408b059bbd8e62fce34544a45c2575968

https://github.com/fortio/proxy/actions/runs/3932404413/jobs/6724921344

**Expected behavior:**

Pick up 1.19.5 and build

**Actual behavior:**

Error: Unable to find Go version 'stable' for platform linux and architecture x64.

**Comment by ldemailly** [comment]
looks like I have the wrong sha, I thought I had dependabot for actions also setup but not on that repo - sorry

**Comment by marko-zivic-93** [comment]
Hello @ldemailly 
Thank you for creating the issue and being proactive about it and figuring the problem out on your own :)
