### ISSUE TITLE
support for new go 1.20

### ISSUE THREAD

**Issue by jason-huang-deltatre** [actions/setup-go#326]
**Description:**
CI failed after I specified the version to go 1.20, here is the error:

Error: perfutils/ballast/ballast.go:6:2: cannot find package "k8s.io/apimachinery/pkg/api/resource" in any of:
	/opt/hostedtoolcache/go/1.2.2/x64/src/pkg/k8s.io/apimachinery/pkg/api/resource (from $GOROOT)
	($GOPATH not set)

I guess it is because setup-go action picked up go version 1.2 by mistake. It should be version 1.20 (since go use semantic versioning). Can you guys please fix that?

**Action version:**
Latest version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by jason-huang-deltatre** [comment]
If i set go 1.20, setup-go will grab go 1.2.2 instead of go 1.20. Issue solved by using tag go 1.20.0

**Comment by cpanato** [comment]
if use `1.20.x` works

**Comment by panticmilos** [comment]
hi @jason-huang-deltatre, thank you for the report, we will take a look at it :)

**Comment by leonbergr** [comment]
I faced similar issue while having go version without apostrophes in gha .yaml file.
ie. good: `go-version: '1.20'`
bad `go-version: 1.20`

This this 1.20 => 1.2 conversion can happened to any value in gha .yaml without apostrophes

**Comment by dmitry-shibanov** [comment]
Hello everyone. I think it is an expected behaviour. You need to specify version like this `go-version: '1.20'`. You can check this comment for more information: https://github.com/actions/setup-python/issues/160#issuecomment-724485470. 

Thank you for your reply @leonbergr. 

For now I'm going to close the issue.

**Comment by cedws** [comment]
I got bitten by this too... goddamn YAML.

**Comment by danielgospodinow** [comment]
Agh, I got bitten by this too. 😆 Damn those pesky YAMLs.

**Comment by xlab** [comment]
![image](https://github.com/actions/setup-go/assets/477998/5f386615-e14a-4879-b5d4-347faa08702a)
