### ISSUE TITLE
Support go1.20

### ISSUE THREAD

**Issue by timandy** [actions/setup-go#330]
**Description:**
Please suppot go1.20

**Justification:**
Go1.20 is identified as go1.2

https://github.com/timandy/go-asm-demo/actions/runs/4111516938

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello @timandy. Thank you for your report. Could you please refer to this [comment](https://github.com/actions/setup-go/issues/326#issuecomment-1415719692) to solve the issue. For now I'm closing it as a duplicate.

**Comment by timandy** [comment]
@dmitry-shibanov Thanks a lot.
