### ISSUE TITLE
Add go 1.20.1

### ISSUE THREAD

**Issue by wader** [actions/setup-go#335]
**Description:**
Add go 1.20.1

**Justification:**
Is the latest stable version

**Are you willing to submit a PR?**
Looking at https://github.com/actions/go-versions/actions it seems like the action used to update new versions is waiting for some kind of approval.

**Comment by jonathan-innis** [comment]
Ping @maxim-lobanov @marko-zivic-93 @MaksimZhukov as they have approval permission for the runner that gets the latest version in the [manifests repo](https://github.com/actions/go-versions)

**Comment by jonathan-innis** [comment]
Newest version should be released for `setup-go` action due to: https://pkg.go.dev/vuln/GO-2023-1571

**Comment by dsame** [comment]
Hello @wader , thanks for the note, we take a look at the issue

**Comment by MaksimZhukov** [comment]
Hello @wader @jonathan-innis !
We have added go `1.20.1`, it is available for use. Thank you for your patience!

**Comment by wader** [comment]
@MaksimZhukov no worries! thanks

**Comment by dmitry-shibanov** [comment]
Hello everyone. You can use it with this snippet:
```yaml
  - uses: actions/setup-go@v3
    with:
      go-version: '1.20'
      check-latest: true
```

For now I'm going to close the issue.
