### ISSUE TITLE
Version 1.19.5 is used instead of 1.19.6 if 1.19 is specified

### ISSUE THREAD

**Issue by lasarojc** [actions/setup-go#337]
**Description:**
Using `go-version: "1.19"` should cause the latest patch version to be used, i.e., `1.19.6`, but `1.19.5` is used instead.

**Action version:**
      `actions/setup-go@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Use the setup-go action to deploy the latest 1.19 go version (`go-version: "1.19"`)
https://github.com/cometbft/cometbft/actions/runs/4233590695/workflow

**Expected behavior:**
Go 1.19.6 should be installed.

**Actual behavior:**
Go 1.19.5 is installed.

**Comment by lasarojc** [comment]
Seems to have been just fixed.
Thanks!

**Comment by lasarojc** [comment]
Actually, this is not fixed.

**Comment by lasarojc** [comment]
The expected behavior is now seen.

**Comment by JohnMaguire** [comment]
@lasarojc Specifying `check-latest: true` solved this for us (Go 1.20.2 -> Go 1.20.3.)

**Comment by brian2269** [comment]
https://github.com/actions/setup-go/issues/337#issuecomment-1500400364

**Comment by lasarojc** [comment]
> @lasarojc Specifying `check-latest: true` solved this for us (Go 1.20.2 -> Go 1.20.3.)

Thanks. I will try it the next time I see this issue.
