### ISSUE TITLE
Installing 1.20 version instead of requested version ^1.16

### ISSUE THREAD

**Issue by gwthm-in** [actions/setup-go#342]
**Description:**
I'm trying to setup github action setup-go to setup go version 1.16 using `go-version: ^1.16`, but it is installing different version altogether. 

**Action version:**
v3

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**
^1.16

**Repro steps:**  
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/8710113/222950741-f123fe5f-1eea-455c-bb92-acc071bd0d3f.png">

**Expected behavior:**
I expected it to install go version 1.16

**Actual behavior:**
But it is installed go version 1.20

**Comment by dmitry-shibanov** [comment]
Hello @gwthm-in. Thank you for your report. According to the documentation the setup-go action uses SemVer notation for go-version input. You use [carpet range](https://github.com/npm/node-semver#caret-ranges-123-025-004) that is why the action sets up Go 1.20. You should use it as `1.16`

For now I'm going to close the issue.
