### ISSUE TITLE
Broken version normalization

### ISSUE THREAD

**Issue by tie** [actions/setup-go#35]
PR #13 broke the way version normalization works. Since it’s merged, now `1.10` resolves to `1.10.8` or whatever the latest version is instead of `1.10.0`. This is *not* the behavior Go user expects.

**Comment by tie** [comment]
See https://github.com/golang/go/issues/32450

**Comment by bryanmacfarlane** [comment]
The version input is a semver spec (not a version input).  So it accepts things like ^1.10.6, ranges etc.

Since it's a semver spec, 1.10 does satisfy 1.10.8 ... https://jubianchi.github.io/semver-check/#/1.10/1.10.8

If you want 1.10.0, then supply the semver spec 1.10.0

**Comment by bryanmacfarlane** [comment]
Closing based on ☝️
