### ISSUE TITLE
V4 not released but written in readme

### ISSUE THREAD

**Issue by jacobdonenfeld** [actions/setup-go#353]
Commit added v4 to readme of the repo, but the release wasn't made and I am running into the following issue:
```
Unable to resolve action `actions/setup-go@v4`, unable to find version `v4`
```

**Comment by dsame** [comment]
hello @jacobdonenfeld , thanks for your input, we started to work on the question, the answer will be provided shortly.

**Comment by dsame** [comment]
Hello @jacobdonenfeld - the release tag is not created yet. The v4 release will be announced in a week, but you can use `@main` for the most recent commits meanwhile.

**Comment by jacobdonenfeld** [comment]
Thank you!
