### ISSUE TITLE
cache restore: do not warn about missing go.sum if go.mod has no require statement

### ISSUE THREAD

**Issue by dolmen** [actions/setup-go#360]
**Description:**
setup-go@v4 on a Go module which has no dependency (no `require` in `go.mod`) and so has no `go.sum`:

Example project: https://github.com/dolmen-go/codegen/blob/master/go.mod

Warning reported:
```
Restore cache failed: Dependencies file is not found in /home/runner/work/.... Supported file pattern: go.sum
```

Example run: https://github.com/dolmen-go/codegen/actions/runs/4543498779

Expected: no warning because this is a false positive.

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [X] Self-hosted

**Tools version:**
Verified with Go 1.12 to 1.20. Other not checked.

**Repro steps:**
A Go module with no dependencies, so no `go.sum`. Example: https://github.com/dolmen-go/codegen/blob/master/go.mod

**Expected behavior:**
No warning

**Actual behavior:**
https://github.com/dolmen-go/codegen/actions/runs/4543498779

<img width="931" alt="Screenshot" src="https://user-images.githubusercontent.com/129536/228251001-85bfb676-a2f0-4a63-b87c-46a7d05bf293.png">

**Comment by marko-zivic-93** [comment]
Hello @dolmen 
Thank you for your issue. We will investigate it and come back to you as soon as we have some info about this 🙂

**Comment by panticmilos** [comment]
hi @dolmen, in the scope of the new [release](https://github.com/actions/setup-go/releases/tag/v4.0.0) we have enabled caching by default. Now if the cache saves or restore fails, the action will only throw the warning but not the error. If you want to avoid these warnings I believe you can only specify `cache: false`, and the warnings should not appear.

I will close this issue for now, if you have any additional questions feel free to continue the conversation here :)
