### ISSUE TITLE
Wrong go version visible in Mac OS

### ISSUE THREAD

**Issue by mageshgv** [actions/setup-go#363]
**Description:**
PATH is not updated with the installed go version's path for Macos runner.

Logs of the version Installed by the action:
```
Successfully extracted go to /Users/runner/work/_temp/b591d26c-4a5c-4496-b4c5-82905c152024
Adding to the cache ...
Successfully cached go to /Users/runner/hostedtoolcache/go/1.19.2/x64
Added go to the path
Successfully set up Go version 1.19.2
go version go1.19.2 darwin/amd64
```

Actually exposed version:

```
which go
/usr/local/bin/go

ls -la /usr/local/bin/go
lrwxr-xr-x  1 runner  admin  29 Mar 18 11:42 /usr/local/bin/go -> /usr/local/opt/go@1.17/bin/go
```

go version visible in the job:
```
go version
go version go1.17.13 darwin/amd64
```

PATH does not have an entry pointing to the location where the go version was installed:
```
echo $PATH
/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bbin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdibrary/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworons/Current/Commands:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks//Current/Commands:/Users/runner/hostedtoolcache/gcloud/424.0.0/x64/bin:/usr/local/opt/bin:/Users/runner/hoste4/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.c/curl/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/droid/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Users/runner/.dotnet/toolbin:/Users/runner/hostedtoolcache/stack/2.9.3/x64:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/stack/2.9.3/x64
```

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ x] macOS
- [ ] Windows

**Runner type:**
- [ x] Hosted
- [ ] Self-hosted

**Tools version:**
1.19.2

**Repro steps:**  
```
- name: Setup Go
        uses: actions/setup-go@v3 (also v2/v4)
        with:
          go-version: "1.19.2"
```

**Expected behavior:**
go version is 1.19.2

**Actual behavior:**
go version is 1.17.13

**Comment by dmitry-shibanov** [comment]
Hello @mageshgv. Thank you for your report. Go from `usr/local/bin` is installed during [images generation](https://github.com/actions/runner-images/blob/main/images/macos/provision/core/golang.sh). I've tried to reproduce the issue but for me it works as expected. Could you please share a public repository to reproduce the issue ?

**Comment by mageshgv** [comment]
Hi @dmitry-shibanov 
Thanks for checking this. I tried to reproduce this with a simple repository and found the root cause of the issue was not in setup-go.

When I reported this issue, I was using upterm session to troubleshoot a failing step and apparently the upterm session used for debug was the culprit.
```
- name: Setup upterm session
      uses: lhotari/action-upterm@v1
```

Closing the issue, thanks again.
