### ISSUE TITLE
0s are ignored at the end of version numbers

### ISSUE THREAD

**Issue by bbp-brieuc** [actions/setup-go#364]
**Description:**
go-version: 1.20 results in installing go 1.2 instead of 1.20

**Action version:**
v2

**Platform:**
- [ x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ x] Hosted
- [ ] Self-hosted

**Tools version:**
1.20.2

**Repro steps:**  
specify go version 1.20 and use functionality that was implemented after 1.2 (eg: context.Context.Cause), it won't compile

**Expected behavior:**
Install go 1.20 instead of 1.2

**Actual behavior:**
Installation of go 1.2 instead of 1.20

**Comment by ziyixi** [comment]
I have also found the same problem. Using `go-version: '>=1.20.0'` can temporarily solve this issue.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Thank you for your report. Could you please refer to this https://github.com/actions/setup-go/issues/326#issuecomment-1415719692 to solve the issue. For now I'm closing it as a duplicate.
