### ISSUE TITLE
Support for go 1.20?

### ISSUE THREAD

**Issue by vademecumuk** [actions/setup-go#365]
**Description:**
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

Actually sets up go 1.2 instead of 1.20

Output:
...
Successfully cached go to /opt/hostedtoolcache/go/1.2.2/x64
Added go to the path
Setting GOROOT for Go version < 1.9
Successfully set up Go version 1.2
...

**Action version:**
v3 & v4 with go 1.20

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

1.20

**Repro steps:**  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

**Expected behavior:**
Go v1.20 is setup

**Actual behavior:**
GO v 1.2 is setup

**Comment by dmitry-shibanov** [comment]
Hello @vademecumuk. Thank you for your report. Could you please refer to this [comment](https://github.com/actions/setup-go/issues/326#issuecomment-1415719692) to solve the issue. For now I'm closing it as a duplicate.
