### ISSUE TITLE
1.x resolves to beta version

### ISSUE THREAD

**Issue by mmcloughlin** [actions/setup-go#37]
Currently this action resolves `1.x` to `1.14.0-beta1`. This is not desirable behavior: `1.x` should resolve to the latest regular release (not `beta` or `rc`).

For an example, see https://github.com/mmcloughlin/avo/runs/373428475.

**Comment by bryanmacfarlane** [comment]
Can you try this with `setup-go@v2-beta`?  I think it should be good as the default is to not select pre-release and I added a stable input which defaults to true.  I think it should be fixed in the v2 versions.

**Comment by bryanmacfarlane** [comment]
Closing since I asserted v2-beta fixes.  If you try it out and find it doesn't let me know and I'll look into it.
