### ISSUE TITLE
check-latest not working. getting 1.20.3 instead of 1.20.4 (forcing 1.20.4 works but defeats "check-latest")

### ISSUE THREAD

**Issue by ldemailly** [actions/setup-go#373]
Run actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
  with:
    go-version: 1.[2](https://github.com/fortio/fortiotel/actions/runs/4867452455/jobs/8681043100#step:5:2)0
    check-latest: true
    token: ***
    cache: true
Setup go version spec 1.20
Attempting to resolve the latest version from the manifest...
matching 1.20...
Resolved as '1.20.[3](https://github.com/fortio/fortiotel/actions/runs/4867452455/jobs/8681043100#step:5:3)'

**Action version:**
4d34df0c2316fe8122ab82dc22947d607c0c91f9
(latest)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.20 wanting 1.20.4

**Repro steps:**  
https://github.com/fortio/fortiotel/blob/main/.github/workflows/releaser.yml

**Expected behavior:**
1.20.4 picked

**Actual behavior:**
1.20.3 picked

**Comment by ldemailly** [comment]
https://github.com/fortio/multicurl/pull/64/files did pick 1.20.4 before retrying the one above that still got 1.20.3

**Comment by dmitry-shibanov** [comment]
Hello @ldemailly. Thank you for your report. We've updated [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json). It should work as expected. For now I'm going to close the issue.

**Comment by ldemailly** [comment]
Thanks, I didn't know this was maintained by hand.

How come that it worked when I put "1.20.4" explicitly, before your update?

**Comment by jan-xyz** [comment]
> How come that it worked when I put "1.20.4" explicitly, before your update?

The README says
```
the action will search for the latest available patch version sequentially in the runner's directory with the cached tools, in the [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json) file or at the go servers.
```

Does that answer your question?

**Comment by ldemailly** [comment]
Same now with 1.20.7 - can you please update, my CI is failing because of govulncheck flagging the security issue in 1.20.6
