### ISSUE TITLE
Go Action template has wrong syntax for Go version

### ISSUE THREAD

**Issue by metalim** [actions/setup-go#387]
**Description:**
Go Action template contains wrong syntax for Go version, without quotes. If user adjusts just the number, it could lead to wrong Go version being used.
Extract of this issue, as the cause was not resolved: https://github.com/actions/setup-go/issues/380#issuecomment-1584588472

**Action version:**
v4.0.1 (latest)

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.20

**Repro steps:** 
1. In Actions: choose [New Workflow]

<img width="498" alt="image" src="https://github.com/actions/setup-go/assets/230431/d39d5260-933f-4565-b4d6-f1948c28fe62">

2. choose Go, Configure

<img width="462" alt="image" src="https://github.com/actions/setup-go/assets/230431/4ecd5859-3869-46a5-a010-d9a41b6da961">

3. observe wrong format is used for version, without quotes:

<img width="335" alt="image" src="https://github.com/actions/setup-go/assets/230431/6a74f8ad-9608-4939-8410-b992f0e8528c">

4. note, that at this point you don't have README at hand, and don't know about the upcoming issue, if you change version to 1.20

**Expected behavior:**
Template should contain version in quotes

**Actual behavior:**
Template contains version without quotes

**Comment by dmitry-shibanov** [comment]
Hello @metalim. Thank you for your report. We'll take a look at it.

**Comment by dmitry-shibanov** [comment]
Hello @metalim. The template was updated. For now I'm going to close the issue.
