### ISSUE TITLE
Test failures on go1.20 with v4, not on v3.2.0

### ISSUE THREAD

**Issue by dolmen** [actions/setup-go#391]
**Description:**

I'm a co-maintainer of Go module `github.com/stretchr/testify`, a major module in the Go ecosystem. I'm trying to migrate `actions/setup-go` from v3.2.0 to v4.

However, on v4 we get test failures with go1.20 which do not appear with setup-go v3.20.
See https://github.com/stretchr/testify/pull/1408

I know that testify testing has concurrency issues (`go test -race -count=100` reports failures on go1.20 on my machine), but I don't see how the changes mentioned in the changelog of setup-go (enable module cache) would affect us.

What changes appeared in v4 that could trigger this?

Note that `testify` is well known for having a circular dependency issue (for which I think I have a fix). Maybe that's related.

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
go1.20

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

https://github.com/stretchr/testify/pull/1408

**Expected behavior:**
Same test success/failure than with actions/setup-go v3.2.0

**Actual behavior:**
Tests failures.

**Comment by dolmen** [comment]
Cc: @SuperQ

**Comment by dusan-trickovic** [comment]
Hello, @dolmen ! Thank you for creating this issue, we will investigate it and see what can be done :)

**Comment by SuperQ** [comment]
I think we already found the source of the issues, the test is flaky due to Go timer race. We have a proposed fix on our side in progress.

https://github.com/stretchr/testify/pull/1412

As to why the new version of the action triggers this race more often, I have no idea. :)

**Comment by dmitry-shibanov** [comment]
Hello @SuperQ. Thank you for your response. In this case I'm going to close the issue. If you have any concerns feel free to ping us.
