### ISSUE TITLE
Get a error when go-version 1.21.x is required

### ISSUE THREAD

**Issue by BorzdeG** [actions/setup-go#398]
**Description:**
I got a error, when I choose to setup go version `1.21.x` in workflow.

![image](https://github.com/actions/setup-go/assets/2332528/7639ab83-e54e-4179-abac-d9fecc643034)

**Action version:**
actions/setup-go@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.21.x

**Repro steps:**  
https://github.com/itbasis/go-clock/blob/test-go-1.21/.github/workflows/test-matrix.yml#L14

**Expected behavior:**
I expect go1.21rc3 version to be received

**Actual behavior:**
`Unable to find Go version '1.21.x' for platform linux and architecture x64.`

**Comment by dmitry-shibanov** [comment]
Hello @BorzdeG. Could you please specify it as: `go-version: 1.21.0-rc.3` ?

**Comment by dsame** [comment]
Hello @BorzdeG i am closing the issue because it looks like to be resolved, but please feel free to reopen it or create new issue if the problem still exists

**Comment by BorzdeG** [comment]
@dsame But the "1.21.x" mask still doesn't work... Or has its support already been repaired?

**Comment by dsame** [comment]
@BorzdeG 

1.21.x is not supposed to work with [node implementation](https://docs.npmjs.com/cli/v6/using-npm/semver) to match 1.21.0-rc.3

```
> const semver = require('semver')
> semver.satisfies('1.21.0','1.21.x')
true
> semver.satisfies('1.21.0-rc.3','1.21.x')
false
> semver.satisfies('1.21.0-rc.3','1.21.0-rc.3')
true
```

Does it answer the question?

**Comment by BorzdeG** [comment]
This falls under the pre-release tag mask: https://docs.npmjs.com/cli/v6/using-npm/semver#prerelease-tags

**Comment by dsame** [comment]
Hello @BorzdeG , in order to match the prerelease and up to the next patch version you should use `~1.21.0-0` matcher

```
> semver.satisfies('1.21.0','~1.21.0-0')
true
> semver.satisfies('1.21.0-rc.1','~1.21.0-0')
true
> semver.satisfies('1.21.1','~1.21.0-0')
true
```
but be aware of
```
> semver.satisfies('1.21.1-rc.1','~1.21.0-0')
false
```

dit it helps?

**Comment by dsame** [comment]
Hello @BorzdeG , i am going to close this issue due to inactivity, but please feel to reopen it or create new on in case if the problem still exists.
