### ISSUE TITLE
Lead inverter switch 

### ISSUE THREAD

**Issue by Guffey666007** [actions/setup-go#401]
Run/ data/JSON files/image boot loader/

**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?*
<details><summary>Details</summary>
<p>

| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell | 

**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**
 
/Gather intelligence on startup prog/disc read/ai
/

</p>
</details> *

**Comment by dusan-trickovic** [comment]
Closing this issue as it seems like spam
