### ISSUE TITLE
Heads up on versioning change for go 1.21.0 that may break setup-go

### ISSUE THREAD

**Issue by WillAbides** [actions/setup-go#406]
Per https://tip.golang.org/doc/go1.21#introduction, starting with 1.21, the initial release for a release family will be styled like go1.N.0 instead of go1.N. This means you will download the next version of go from https://go.dev/dl/go1.21.0.darwin-amd64.tar.gz instead of https://go.dev/dl/go1.21.darwin-amd64.tar.gz.

After spending a few minutes looking through this repo and actions/go-versions, I'm unclear if this will require a change, but I wanted to get the issue out here in case it does.

**Comment by dsame** [comment]
Hello @WillAbides , thank you for you warning, we are starting reviewing the issue

**Comment by WillAbides** [comment]
Looks like setup-go weathered the go1.21.0 release just fine.
