### ISSUE TITLE
pam

### ISSUE THREAD

**Issue by 9777410929** [actions/setup-go#409]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by MaksimZhukov** [comment]
Hello @9777410929 
Please provide us with the issue description and we will reopen it
