### ISSUE TITLE
go-version-file not respecting defaults.run.working-directory

### ISSUE THREAD

**Issue by nickzelei** [actions/setup-go#419]
**Description:**
I am running inside a mono-repo and have a job that sets the default working directory to a folder.
The `go-version-file` is set to point to `go.mod`, but it cannot find it unless I specify the `go-version-file` to also include the working directory.

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

1.21

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
I've setup an example repo that reproduces this.
I have two jobs, both set the default working dir, one does not set the path in `go-version-file`, the other does.
https://github.com/nickzelei/goversion-workdir/pull/1
https://github.com/nickzelei/goversion-workdir/actions/runs/5980795503

Note, the sub directory and presence of `go.work` is intentional here. My main repository is a mono-repo with multiple go projects in sub-directories.
I have different jobs that trigger based on sub-paths changed and use the working dir here so they can operate in isolation.

**Expected behavior:**
The working directory should be honored.

**Actual behavior:**
The setup action is failing claiming it can't find the `go.mod` file. However, if you add a step and `ls- l` the directory, it is clearly there.

**Comment by nickzelei** [comment]
Perhaps I'm making an assumption that I shouldn't be. Github Actions says that it is run any step that uses `run`. I assumed that eventually all action steps invoked `run`, but maybe that is incorrect, and specifying the workdir for this step is intentional.

If so, I can close this issue.

**Comment by dsame** [comment]
Hello @nickzelei , thanks for the note, we are starting to investigate the problem.

**Comment by dsame** [comment]
Hello @nickzelei , you are right: this configuration relates only to `run` step.

Did this answer help?

**Comment by nickzelei** [comment]
I think so, yea. I'll go ahead and close this comment.
