### ISSUE TITLE
Update actions/go-versions stable go version to 1.21 on arm64

### ISSUE THREAD

**Issue by rowland66** [actions/setup-go#423]
### Description

The stable go version on arm64 is out of date and should in sync with the amd64 version.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

The stable label should return the same go version on amd64 and arm64

### Actual behavior

The stable label returns different go version on amd64 and arm64

### Repro steps

N/A

**Comment by mikhailkoliada** [comment]
@dmitry-shibanov @MaksimZhukov hey guys, looks relevant to you :)

**Comment by dmitry-shibanov** [comment]
Hello @rowland66. We updated the versions-manifest with the latest version of Go 1.21 on arm64. Could you please check if it works you as expected?

**Comment by dsame** [comment]
Hello @rowland66 , I am closing the issue due to inactivity. However, please feel free to reopen it or create a new one if the problem still exists.
