### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/root/gocode'

### ISSUE THREAD

**Issue by schniggie** [actions/setup-go#425]
**Description:**
setup-go stopped working on the same self-hosted runner it worked for months. Runner started as non root user with passwordless sudo allowed, which worked without any issues till some days ago:

**Action version:**
v3 and v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

See log:
```
0s
Run actions/setup-go@v4
  with:
    go-version: [1](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/6212870763/job/16863427537#step:3:1).[2](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/6212870763/job/16863427537#step:3:2)0.x
    check-latest: false
    token: ***
    cache: true
Setup go version spec 1.20.x
Found in cache @ /home/cd/actions-runner/_work/_tool/go/1.20.7/x6[4](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/6212870763/job/16863427537#step:3:4)
Added go to the path
Successfully set up Go version 1.20.x
Error: EACCES: permission denied, mkdir '/root/gocode'
```

Any idea?

**Comment by dsame** [comment]
Hello @schniggie, we are starting to investigate the issue

**Comment by dsame** [comment]
Hello @schniggie , can you please run the build with [debug turned on](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging) and attach the logs of `setup-go` action?

**Comment by dsame** [comment]
Hello @schniggie , can you please double check the environment variable GOPATH  was not set or changed on the runner host recently?

**Comment by dsame** [comment]
The problem is not reproducible, and works as expected with the current action:

https://github.com/akv-demo/test-setup-go/actions/runs/6653482897/job/18079543231

**Comment by dsame** [comment]
Hello @schniggie , i am closing the issue due to inactivity, but please feel free to reopen it or create the new one in case if the problem still exists
