### ISSUE TITLE
Berroe8

### ISSUE THREAD

**Issue by Berro8** [actions/setup-go#444]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dsame** [comment]
The empty issue is closed as a spam
