### ISSUE TITLE
ENOENT: no such file or directory, mkdir '/home/runner' in macos-latest

### ISSUE THREAD

**Issue by davidkhala** [actions/setup-go#448]
**Description:**
when use action as below in macos-latest
```
...
- uses: actions/setup-go@main
  with:
          go-version: 'stable'
```

See error with message
`ENOENT: no such file or directory, mkdir '/home/runner'`

**Action version:**

actions/setup-go@main (as of 19 Dec 2023)

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
> go-version: 'stable'
go 1.21.5 as of today.

**Repro steps:**  
https://github.com/davidkhala/ci-cd-utils/blob/f91037f96fd92ed1384819d034b98879789b7a69/.github/workflows/environment.yml#L57C26-L57C26

**Expected behavior:**
success without error

**Actual behavior:**
Error prompts in 
https://github.com/davidkhala/ci-cd-utils/actions/runs/7259364146/job/19776506433#step:10:23

**Comment by dsame** [comment]
Hello @davidkhala ,
the workflow [enforces](https://github.com/davidkhala/ci-cd-utils/blob/f91037f96fd92ed1384819d034b98879789b7a69/.github/workflows/environment.yml#L6)  the HOME environment variable to be set to `/home/runner/work/` which is not correct for the macos (it is [supposed](https://github.com/akv-demo/test-setup-go/actions/runs/7336751033/job/19976559961#step:2:14) to be `/Users/runner`)

Removing the setting the HOME variables lets the build to pass: https://github.com/akv-demo/test-setup-go/actions/runs/7336751033/job/19976559961

did it helps?

**Comment by davidkhala** [comment]
Thanks for reminds. It is my fault.
