### ISSUE TITLE
Add option to install gcc

### ISSUE THREAD

**Issue by torkelrogstad** [actions/setup-go#45]
Some Go programs need gcc installed to compile. It would be nice if this actions let us do that.

**Comment by bryanmacfarlane** [comment]
The hosted image has gcc.  I don't think the setup-go action should install anything.  If anything, there should be a setup-gcc action and if you're program is known to need go and gcc, then that workflow would add both of them.

**Comment by cep21** [comment]
Note: This is very important for self hosted runners.  Most go programs and linters will fail without GCC to the point I can't image it not being a requirement for any project of complexity.

Also maybe relevant, there is independent work to reduce the set of pre installed dependencies in actions runners: https://github.com/actions/virtual-environments/discussions/3242#discussioncomment-648545
