### ISSUE TITLE
How to run tests with latest golang version

### ISSUE THREAD

**Issue by fredmaggiowski** [actions/setup-go#455]
**Description:**

Hi, I can't find a way to make my action run against the latest golang version available.

I want to run tests against stable golang releases but also verify that newer golang version do not provide harm to my codebase, for this reason I've setup my action to run on a version matrix and then have a "special job" that I want to run tests on the very latest golang release.

This is my setup:

```yaml
      - name: Use golang ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          check-latest: true
```

What I'd expect from this is that used golang version would be something > go1.22, instead I see golang 1.20 is being used.

Even adding `cache: false` makes my action run with golang 1.20

I understand this might not be a bug but just me not understanding the doc, but how am I supposed to reach my goal? 

**Action version:**

actions/setup-go@v5

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  

Action current configuration on main branch: 

https://github.com/rond-authz/rond/blob/07099709a5968c4617c9342716b64d9e077b38f7/.github/workflows/test.yml#L53-L55 

PR where I'm trying to fix the behavior:

https://github.com/rond-authz/rond/pull/320/files

Action result showing golang 1.20 is being used:

https://github.com/rond-authz/rond/actions/runs/7816281593/job/21321451154?pr=320#step:3:9

<img width="772" alt="Screenshot 2024-02-07 alle 15 33 02" src="https://github.com/actions/setup-go/assets/7142570/421e1d7e-1fbb-468b-9b0d-2cdbc306b6eb">

**Expected behavior:**

My test-latest job should run with the latest golang release avilable

**Actual behavior:**

not the latest is being used, regardless of the cache (apparently)

**Comment by spencerschrock** [comment]
I believe you're confusing two caches: the tool cache vs the build/package cache, which the argument is for [README link](https://github.com/actions/setup-go/blob/6c1fd22b67f7a7c42ad9a45c0f4197434035e429/README.md#caching-dependency-files-and-build-outputs).

It sounds like what you want are the `stable` and `oldstable` aliases, which are mentioned in the README [here](https://github.com/actions/setup-go/blob/6c1fd22b67f7a7c42ad9a45c0f4197434035e429/README.md#using-stableoldstable-aliases).

**Comment by aparnajyothi-y** [comment]
Hello @spencerschrock, Thank you for creating the issue and we will look into it :)

**Comment by aparnajyothi-y** [comment]
Hello @spencerschrock, Thank you once again for creating this issue
If we want to test with versions of Go that are not yet stable, you can specify the exact version in the with.go-version field of your workflow file. This field supports the 1.x syntax, so you can use 1.23.x to test with the latest release of Go 1.23, including any release candidates. Please refere [this document](https://github.com/actions/setup-go/blob/6c1fd22b67f7a7c42ad9a45c0f4197434035e429/README.md?plain=1#L33)


The actions/setup-go action is designed to download and set up a Go environment of any version specified in the go-version input of the action. The action uses the official Go downloads, which include both stable and unstable versions. 
However, the actions/setup-go action only supports versions that are available in the [go-versions](https://github.com/actions/go-versions) repository.
However, it's important to note that using non-stable versions may lead to potential instability in your workflows, as they may have not been fully tested or may contain bugs. The best practice is to use stable versions for production code.

**Comment by gaby** [comment]
@fredmaggiowski This is what I use:

```yaml
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v5
    with:
      go-version: 'stable'
      check-latest: true
  - run: go run hello.go
```

**Comment by aparnajyothi-y** [comment]
Hello @spencerschrock, Please confirm that the above clarification is helpful to proceed to close the issue.

**Comment by spencerschrock** [comment]
I'm not the issue author, I'm assuming you meant @fredmaggiowski

**Comment by fredmaggiowski** [comment]
> I'm not the issue author, I'm assuming you meant @fredmaggiowski

I guess you are right lol

> Hello @spencerschrock, Please confirm that the above clarification is helpful to proceed to close the issue.

Yes @aparnajyothi-y sorry for the delay, I had a few busy weeks; i'm verifying it later today and come back at you asap :)

**Comment by fredmaggiowski** [comment]
It seems to work, thanks!

**Comment by tamird** [comment]
> Hello @spencerschrock, Thank you once again for creating this issue If we want to test with versions of Go that are not yet stable, you can specify the exact version in the with.go-version field of your workflow file. This field supports the 1.x syntax, so you can use 1.23.x to test with the latest release of Go 1.23, including any release candidates. Please refere [this document](https://github.com/actions/setup-go/blob/6c1fd22b67f7a7c42ad9a45c0f4197434035e429/README.md?plain=1#L33)

Hi @aparnajyothi-y. It seems that [the manifest](https://github.com/actions/go-versions/blob/main/versions-manifest.json) doesn't include any non-stable versions. Neither betas nor release candidates. Is that still meant to be a supported use case? See https://github.com/petermattis/goid/pull/50 where I tried unsuccessfully to add go1.23rc2 to the matrix.

**Comment by nikicat** [comment]
Hello, how can I build with go 1.23rc2?

**Comment by nikicat** [comment]
Figured it out: just specify `go-version: 1.23.0-rc.2` instead of 1.23rc2
