### ISSUE TITLE
Signing key has expired

### ISSUE THREAD

**Issue by lpar** [actions/setup-go#463]
**Description:**

The key used to sign the v5.0.0 release has expired.

![CleanShot 2024-03-07 at 09 48 57@2x](https://github.com/actions/setup-go/assets/857035/75e040f7-90af-46ad-bf3f-c7bf0612522b)

From looking at [actions/setup-node](https://github.com/actions/setup-node/releases/tag/v4.0.2), it looks like an unexpired signing key B5690EEEBB952194 is available.

(I thought about entering this as a security issue, but as long as the expired key has been kept secure anyway...)

**Comment by HarithaVattikuti** [comment]
Hello @lpar
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priya-kinthali** [comment]
Hello @lpar 👋,
Thank you for your keen observation!
We're pleased to inform you that the signing key issue has been addressed. Current releases are now signed with GitHub’s verified signature (GPG key ID: B5690EEEBB952194). We appreciate your involvement in the community and look forward to your continued contributions :)

**Comment by rudushi4** [comment]
wow

**Comment by nonnoy0330-crypto** [comment]
["Extension: Atom Material Icons - Workspace - Visual Studio Code" https://vscode.dev?vscode-lang=th](url)

**Comment by abdallh12345** [comment]
https://github.com/abdallh12345/setup-go/abdallh12345/463
