### ISSUE TITLE
Green wallet

### ISSUE THREAD

**Issue by Wikivu** [actions/setup-go#492]
https://github.com/actions/setup-go/blob/0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32/CODEOWNERS#L1  etiket: bc1qgn7605ezpwvgmehmvsmj0xhz06qh54ajrmen94 Bu adrese yönlendirme akışlar

**Comment by Wikivu** [comment]
Bu sayfa ile bağlantılı depolar bu adrese akış saglasın

**Comment by HarithaVattikuti** [comment]
Closing as spammy
