### ISSUE TITLE
Shared objects built by Github Actions are very slow to use

### ISSUE THREAD

**Issue by mpenkov** [actions/setup-go#499]
**Description:**

I've identified a problem with building shared libraries from Go source using Github Actions.

The library source contains a single function, called cNoop, which does nothing. I then build this library into a shared object using Github Actions. The workflow is [here](https://github.com/mpenkov/go-shared/blob/master/.github/workflows/build.yml). Nothing fancy, just a `go build -buildmode=c-shared`.

The problem is that the resulting shared object is extremely slow to use. Calling the cNoop function 1 million times from e.g. Python takes nearly 30s.

In contrast, if I build the shared object locally on my machine, the same task (1 million calls to cNoop) takes a fraction of a second.

```
$ RUNPY_LIB_PATH=builds/lib.so.gha2 python run.py  # github actions, build 2
made 1000000 calls in 33.91s
$ RUNPY_LIB_PATH=builds/lib.so.local python run.py # local build
made 1000000 calls in 0.26s
```

Minimum reproducible example is [here](https://github.com/mpenkov/go-shared).

**Action version:**

5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

1.23.0

**Repro steps:**
  
https://github.com/mpenkov/go-shared

**Expected behavior:**

The shared object should be reasonably fast to use.
Here's an example of a shared object that I built locally:

```bash
$ RUNPY_LIB_PATH=builds/lib.so.local python run.py # local build
made 1000000 calls in 0.26s
```

**Actual behavior:**

The shared object built using Github Actions is extremely slow (up to 100 times slower).

```bash
$ RUNPY_LIB_PATH=builds/lib.so.gha2 python run.py  # github actions, build 2
made 1000000 calls in 33.91s
```

**Comment by gowridurgad** [comment]
Hello @mpenkov ,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by mpenkov** [comment]
Hi @priyagupta108 , thank you for looking into this.

Can you get the Ubuntu GHA runner to produce a similar running time? Perhaps the problem is isolated to the Ubuntu runner?

Also, I think you may be misunderstanding the problem because your explanation focuses on the **execution environment**. The point isn't to run the shared library on GHA. The point is to **build** the shared library on GHA, and then to use the shared library in the production environment.

The issue demonstrates that there is something wrong with the way that GHA is **building** the shared library. If I try to use the shared library built by GHA, it is very slow. If I replace the shared library built by GHA with one that I built somewhere else, then it is no longer slow. Therefore, the problem is with GHA.

**Comment by priyagupta108** [comment]
Hi @mpenkov 👋 ,
Could you please provide the Go version installed in your local environment (use `go version` to obtain this).
This information will help us investigate the performance difference between the shared libraries built on GitHub Actions and local machine.
Thank you!

**Comment by mpenkov** [comment]
```
$ go version
go version go1.21.4 linux/amd64
```

**Comment by priyagupta108** [comment]
Hi @mpenkov,
After further investigation, I've identified a performance issue related to Go versions released from [2024-07-02](https://go.dev/doc/devel/release#:~:text=go1.22.5%20(released%202024%2D07%2D02)%20includes%20security%20fixes%20to%20the%20net/http%20package%2C%20as%20well%20as%20bug%20fixes%20to%20the%20compiler%2C%20cgo%2C%20the%20go%20command%2C%20the%20linker%2C%20the%20runtime%2C%20and%20the%20crypto/tls%2C%20go/types%2C%20net%2C%20net/http%2C%20and%20os/exec%20packages.%20See%20the%20Go%201.22.5%20milestone%20on%20our%20issue%20tracker%20for%20details) onwards. On Ubuntu environments, the execution time is notably longer with these versions compared to those released before this date.
Please find the test results below:
**Versions from July 2, 2024, onwards:**
* **go1.23.1**:<br>
  <img width="530" alt="Screenshot 2024-09-19 at 3 44 33 PM" src="https://github.com/user-attachments/assets/2f37b03f-0ad6-4441-a708-30139aec2429">


* **go1.22.5**:<br>
  <img width="530" alt="Screenshot 2024-09-19 at 3 45 25 PM" src="https://github.com/user-attachments/assets/366a88ed-ec1c-409e-bca5-92ec165cadd2">


**Versions released before July 2, 2024:**
* **go1.22.4**:<br>
  <img width="529" alt="Screenshot 2024-09-19 at 3 00 50 PM" src="https://github.com/user-attachments/assets/06e7984c-8277-4f68-962f-70a9377a44ce">

* **go1.21.4**: <br>
  <img width="529" alt="Screenshot 2024-09-19 at 2 58 40 PM" src="https://github.com/user-attachments/assets/951aef3c-bc90-44d4-8343-4ed766c0d0b0">

I recommend setting a Go version released before July 2, 2024, such as 1.21.4, in the GitHub Actions workflow to observe the performance difference.

**Comment by mpenkov** [comment]
Good catch! So this is a problem with the go utility itself, and not Github Actions?

**Comment by priyagupta108** [comment]
Thank you! Yes, this is an issue with the Go utility itself. The https://github.com/golang/go/issues/68587 issue you referenced is relevant and might be worth following for any updates or potential fixes from the Go team.
Closing this issue for now. Please feel free to reach out to us in case of any concerns.
