### ISSUE TITLE
0x678fcf657e1e90658d540bca155bca7ydf8f512b

### ISSUE THREAD

**Issue by krylov-krylov** [actions/setup-go#512]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by priya-kinthali** [comment]
Closing this issue as it appears to be spam.
