### ISSUE TITLE
readme: recommend double rather than single quotes in YAML files

### ISSUE THREAD

**Issue by mcandre** [actions/setup-go#513]
**Description:**

YAML breaks conventions for escape characters in at least one of its three string syntaxes. For this reason, recommend using double quotes (`"test"`) for string values, rather than single quotes (`'test'`) or bare, unquoted strings (`test`).

**Action version:**

N/A

**Platform:**

N/A

**Runner type:**

N/A

**Tools version:**

N/A

https://yaml.org/spec/

**Comment by gowridurgad** [comment]
Hello @mcandre ,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by priyagupta108** [comment]
Hi @mcandre 👋,
The [YAML specification](https://yaml.org/spec/1.2/spec.html) doesn't seem to specifically encourage using double quotes.
In YAML, both single quotes ' and double quotes " can be used to denote string values, but they have different behaviors:
* Single quotes allow almost any character in your string and won't parse escape codes. For example, '\n' would be interpreted literally as the string \n.
* Double quotes parse escape codes, so "\n" would be interpreted as a line feed character.

The choice between single and double quotes depends on the specific use case. If you need to include escape sequences in your string, you should use double quotes. If you want your string to be interpreted exactly as it is, you should use single quotes. Single quoted strings work for all scenarios In general.

Both quoting styles are widely accepted and used in YAML files. The choice between them often comes down to personal preference and the specific needs of your project. Therefore, there is nothing incorrect about the usage in the README file.

**Comment by priyagupta108** [comment]
Thank you for sharing your perspective, but I’d like to clarify that the [YAML specification](https://yaml.org/spec/1.2/spec.html) does not deprecate single quote syntax, and both single and double quotes are valid for string values, depending on the use case. 

That said, I’m curious—is there a broader consensus or any official documentation suggesting that non-double quote syntax should be deprecated for safety reasons or that it’s generally hazardous? I’d really appreciate any insights or references you can provide on this.

**Comment by mcandre** [comment]
The YAML spec doesn't recommend any particular file extension, either. It's an important document but does not answer every question about ideal YAML usage. Just because the spec offers a jumpable bridge does not mean we should apply it.

**Comment by priyagupta108** [comment]
Hi @mcandre ,
Thank you for your suggestion! We truly appreciate your input.
In the `setup-go` README, single quotes are used for simple strings, such as version numbers, where no special characters or escape sequences are required. This approach helps keep the examples clear, concise, and easy to follow.
Additionally, the [GitHub Actions workflow syntax documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions) doesn’t enforce a particular quoting style, and the choice between single and double quotes typically depends on the specific use case.
At this time, we don't feel a change is necessary for the `setup-go` action. However, if you're encountering any specific issues with the current examples in the README, please feel free to share more details, and we’d be happy to look into it!

**Comment by mcandre** [comment]
Most programming languages support C-style escape characters in (single quoted) strings. YAML does not. Such sequences are interpreted differently, and the user has to remember up to three different semantics. That's not simple.

For this reason, it is hazardous to use non-double quoted strings for YAML content. Following a rule of using only double-quoted strings is safe and simple.

**Comment by priyagupta108** [comment]
@mcandre, Thank you for sharing your thoughts! 
At this time, we do not plan to change the quoting style in the README. Single quotes are used for basic strings like version numbers, where escape sequences or special characters are not involved, making the examples clear and simple.
Since quoting style can vary based on individual use cases, we prefer not to make a strict recommendation in the README. 
I'm going to close this issue for now, but we'll keep it in mind if it becomes a recurring request in the future.

Thanks again for your inputs!

**Comment by mcandre** [comment]
Having to remember three different syntaxes for three different purposes is the opposite of simplicity.
