### ISSUE TITLE
Overriding go-version with latest regardless of settings

### ISSUE THREAD

**Issue by ross-spencer** [actions/setup-go#516]
**Description:**

I have the following configured:

```yaml
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: go version
```

But in GitHub the workflow is always downloading 1.23.3:

```text
Run actions/setup-go@v5
Setup go version spec 1.22
Found in cache @ /opt/hostedtoolcache/go/1.22.9/x64
Added go to the path
Successfully set up Go version 1.22
go: downloading go1.23.3 (linux/amd64)
/opt/hostedtoolcache/go/1.22.[9](https://github.com/ocfl-archive/error/actions/runs/11952824712/job/33319397499#step:4:10)/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.22.9/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Cache is not found
go version go1.23.3 linux/amd64
```

**Action version:**

V5.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Expected 1.22 getting 1.23.3

**Repro steps:**  

Currently running in this PR here: https://github.com/ocfl-archive/error/pull/1/files#diff-717013d02a8afac81852f25ba8ecd3cc0ca53a7f1fe25bedebfd66d6f518d21c

**Expected behavior:**
A description of what you expected to happen.

Configuration of Go version should work.

**Actual behavior:**
A description of what is actually happening.

It looks like Go 1.22 is successfully installed and then it is overridden by 1.23. It shows up quite profoundly in this workflow because staticcheck is not compiled for 1.23.

**Comment by aparnajyothi-y** [comment]
Hello @ross-spencer, Thank you for creating this issue and we will look into it :)

**Comment by mahalakshmi-rekadi** [comment]
Hello @ross-spencer,

**Comment by ross-spencer** [comment]
Thanks for looking at this in-depth @mahalakshmi-rekadi I appreciate it! I will need to think about how to perform multi-version testing but this should stabilize things for now. I will take a look at my settings again this week, this helps a lot.
