### ISSUE TITLE
Caret in go-version value does not work as documented

### ISSUE THREAD

**Issue by panchoh** [actions/setup-go#57]
Hi!

Specifying `go-version` with a caret (e.g. `'^1.14.3'`) does not work as shown in the documentation. `setup-go` desists to download `1.14.1` and proceeds to download the latest stable available (`1.14.4`) as of today.

This can be seen in the logs as:

<details>

    Run actions/setup-go@v2
      with:
        go-version: ^1.14.3
        stable: true
    Setup go stable version spec ^1.14.3
    A version satisfying ^1.14.3 not found locally, attempting to download ...
    Downloading from https://storage.googleapis.com/golang/go1.14.4.linux-amd64.tar.gz
</details>

We suggest updating the docs to drop the mention of the caret.

Hope that it helps!

Cheers,

pancho

EDIT: should have said: "desists to download `1.14.3`".

**Comment by shihanng** [comment]
Based on https://www.npmjs.com/package/semver#caret-ranges-123-025-004:
`^1.14.3` := `>=1.14.3 <2.0.0-0`
so, not downloading version `1.14.1` is the correct behaviour?

**Comment by panchoh** [comment]
> Based on https://www.npmjs.com/package/semver#caret-ranges-123-025-004:
> `^1.14.3` := `>=1.14.3 <2.0.0-0`
> so, not downloading version `1.14.1` is the correct behaviour?

Ouch!  Now I understand. So, `setup-go` is working perfectly.  My brain was not :-)

Thanks for the enlighthenment, @shihanng !
