### ISSUE TITLE
Produce error instead of silently ignoring empty "go-version"

### ISSUE THREAD

**Issue by thaJeztah** [actions/setup-go#83]
I'm not sure if it's possible for an action to distinguish between a value _not being set_ or a value _being set, but empty / nil_, but opening a ticket, just in case. This could also be considered a bug in GitHub actions (more below).

I ran into a bug yesterday in one of our repositories using this action (https://github.com/moby/term/pull/19). The repository had a workflow defined as below (simplified);

```yaml
strategy:
  matrix:
    go-versions: [1.12.x, 1.13.x, 1.14.x]
steps:
- name: Install Go
  uses: actions/setup-go@v1
  with:
    go-version: ${{ matrix.go-version }}
```

CI seemed to be running fine, testing all versions:

<img width="854" alt="Screenshot 2020-11-01 at 12 38 59" src="https://user-images.githubusercontent.com/1804568/97801803-a57ecc80-1c3f-11eb-821c-2174e8cfef8b.png">

However, on close inspection, it turned out **we were only testing against the latest go version**. The reason for that was that the `go-version:` was empty:

<img width="340" alt="97782034-7c066800-1b8f-11eb-9a57-e6498d247409" src="https://user-images.githubusercontent.com/1804568/97801857-06a6a000-1c40-11eb-9729-1dc96bb0a1f6.png">

The reason was that the matrix defined `go-versions` (plural), but the action was looking for `${{ matrix.go-version }}` (singular), which would be a simple fix;

```patch
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,7 +4,7 @@ jobs:
       matrix:
-        go-versions: [1.12.x, 1.13.x, 1.14.x]
+        go-version: [1.12.x, 1.13.x, 1.14.x]
         platform: [ubuntu-latest]
```

These things can be easy to miss though, as the action is silently ignoring this case; would it be possible to detect this situation and make the action _fail_ ?

**Comment by Emad980** [comment]
https://github.com/actions/setup-go/issues/83

**Comment by IvanZosimov** [comment]
Hi, @thaJeztah 👋 Thank you for this issue! Let me clarify the situation here: If the input 'go-version' is not specified or is an empty string the expected behaviour of the action is to use Go version which is preinstalled as [default version](https://github.com/actions/virtual-environments/blob/main/images/linux/toolsets/toolset-1804.json#L40-L49) on the runner. Since a lot of our customers get used to relying on this expected behaviour unfortunately we can't make the action to fail.

**Comment by thaJeztah** [comment]
Would this be something to consider for a v4 ? (require `latest` to be explicitly set if you don't want a specific version)?
