### ISSUE TITLE
go test ./... always passed (windows)

### ISSUE THREAD

**Issue by astrizhachuk** [actions/setup-go#88]
![image](https://user-images.githubusercontent.com/25724999/100474151-04295000-30f1-11eb-820c-4571ef41284d.png)

**Comment by astrizhachuk** [comment]
@Sergey-Murtazin hi, look at this
https://github.com/onec-cli/cli/runs/4067045549?check_suite_focus=true

**Comment by Sergey-Murtazin** [comment]
Hi @astrizhachuk

I've reproduced your problem.
In the workflow file I've used `go test -short` instead your `go test -test.short`
https://github.com/Sergey-Murtazin/cli/actions/runs/1444648363

Please check if it works for you

**Comment by astrizhachuk** [comment]
@Sergey-Murtazin it works. thx
