### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by hazcod** [actions/setup-go#95]
Hi, in regards to https://github.com/hazcod/enpass-cli/issues/97 I would like to try cross-compilation using GitHub Actions.
Any idea how this can be done with the setup-go workflow?

**Comment by Sergey-Murtazin** [comment]
Hi, @hazcod !

The goal of the `setup-go` action is to install the go compiler.
After its installation, you can compile code for any `dist` the installed go version support.

As my advice you can use a separate run step with 
```
GOOS=darwin GOARCH=arm64 go build
GOOS=linux GOARCH=amd64 go build
GOOS=windows GOARCH=amd64 go build
```
commands or run bash script with them

Hope it helps you

**Comment by Sergey-Murtazin** [comment]
I close this issue because it's stale

Feel free to contact us if you have any questions!
